apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-postgres
  namespace: n8n
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: n8n-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: /n8n/POSTGRES_USERNAME
    - secretKey: password
      remoteRef:
        key: /n8n/POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-backup-s3-account
  namespace: n8n
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: n8n-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: /n8n/BACKUP_S3_ACCESS_KEY
    - secretKey: secret_key
      remoteRef:
        key: /n8n/BACKUP_S3_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secret-env
  namespace: n8n
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: n8n-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_TYPE: postgresdb
        DB_POSTGRESDB_HOST: n8n-cluster-rw
        DB_POSTGRESDB_PORT: "5432"
        DB_POSTGRESDB_DATABASE: n8n
        DB_POSTGRESDB_USER: "{{ .username }}"
        DB_POSTGRESDB_PASSWORD: "{{ .password }}"
        N8N_ENCRYPTION_KEY: "{{ .encryption_key }}"

        N8N_SMTP_HOST: smtp.gmail.com
        N8N_SMTP_PORT: "587"
        N8N_SMTP_USER: "{{ .smtp_username }}"
        N8N_SMTP_PASS: "{{ .smtp_password }}"
        N8N_SMTP_SENDER: no-reply@${EXTERNAL_DOMAIN}
        N8N_SMTP_SSL: "false"
        N8N_SMTP_STARTTLS: "true"
  data:
    - secretKey: username
      remoteRef:
        key: /n8n/POSTGRES_USERNAME
    - secretKey: password
      remoteRef:
        key: /n8n/POSTGRES_PASSWORD
    - secretKey: encryption_key
      remoteRef:
        key: /n8n/ENCRYPTION_KEY
    - secretKey: smtp_username
      remoteRef:
        key: /n8n/SMTP_USERNAME
    - secretKey: smtp_password
      remoteRef:
        key: /n8n/SMTP_PASSWORD
