apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: paperless-dragonfly
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.40.2@sha256:18afa43e911f1dff18c7d1eb452361876d9702bb1cdff5c5d75c69617a4065c9
  replicas: 2
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: paperless-dragonfly
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
  authentication:
    passwordFromSecret:
      name: paperless-dragonfly-credentials
      key: DRAGONFLY_PASSWORD
  resources:
    requests:
      cpu: 15m
      memory: 32Mi
    limits:
      memory: 512Mi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: &app paperless-dragonfly
  labels:
    group: dragonfly
    app: *app
spec:
  selector:
    matchLabels:
      app: *app
  podTargetLabels:
    - app
  podMetricsEndpoints:
    - port: admin
