apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-postgres
  namespace: paperless
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: paperless-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: /paperless/POSTGRES_USERNAME
    - secretKey: password
      remoteRef:
        key: /paperless/POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-redis
  namespace: paperless
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: paperless-redis-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: /paperless/REDIS_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-backup-s3-account
  namespace: paperless
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: paperless-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: /paperless/BACKUP_S3_ACCESS_KEY
    - secretKey: secret_key
      remoteRef:
        key: /paperless/BACKUP_S3_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret-env
  namespace: paperless
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: paperless-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PAPERLESS_ADMIN_USER: "{{ .admin_username }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .admin_password }}"
        PAPERLESS_SECRET_KEY: "{{ .secret_key }}"
        PAPERLESS_REDIS: |-
          redis://:{{ .redis_password }}@paperless-redis-master:6379
        # Database
        PAPERLESS_DBHOST: paperless-cluster-rw
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBNAME: paperless
        PAPERLESS_DBUSER: "{{ .username }}"
        PAPERLESS_DBPASS: "{{ .password }}"
        PAPERLESS_EMAIL_HOST: smtp.gmail.com
        PAPERLESS_EMAIL_PORT: "587"
        PAPERLESS_EMAIL_USE_TLS: "true"
        PAPERLESS_EMAIL_HOST_USER: "{{ .smtp_username }}"
        PAPERLESS_EMAIL_HOST_PASSWORD: "{{ .smtp_password }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
          {
            "openid_connect": {
              "OAUTH_PKCE_ENABLED": true,
              "APPS": [
                {
                  "provider_id": "authentik",
                  "name": "authentik",
                  "client_id": "{{.client_id}}",
                  "secret": "{{.client_secret}}",
                  "settings": {
                    "server_url": "https://authentik.${EXTERNAL_DOMAIN}/application/o/paperless/.well-known/openid-configuration",
                    "fetch_userinfo": true
                  }
                }
              ],
              "SCOPE": ["openid", "profile", "email"]
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: /paperless/POSTGRES_USERNAME
    - secretKey: password
      remoteRef:
        key: /paperless/POSTGRES_PASSWORD
    - secretKey: secret_key
      remoteRef:
        key: /paperless/SECRET_KEY
    - secretKey: redis_password
      remoteRef:
        key: /paperless/REDIS_PASSWORD
    - secretKey: admin_username
      remoteRef:
        key: /paperless/ADMIN_USERNAME
    - secretKey: admin_password
      remoteRef:
        key: /paperless/ADMIN_PASSWORD
    - secretKey: smtp_username
      remoteRef:
        key: /paperless/SMTP_USERNAME
    - secretKey: smtp_password
      remoteRef:
        key: /paperless/SMTP_PASSWORD
    - secretKey: client_id
      remoteRef:
        key: /paperless/OIDC_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: /paperless/OIDC_CLIENT_SECRET
