apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-env
  namespace: authentik
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: authentik-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .secret_key }}"
        DB_USERNAME: "{{ .dbuser }}"
        DB_PASSWORD: "{{ .dbpass }}"
  data:
    - secretKey: secret_key
      remoteRef:
        key: /authentik/SECRET_KEY
    - secretKey: dbuser
      remoteRef:
        key: /authentik/POSTGRES_USERNAME
    - secretKey: dbpass
      remoteRef:
        key: /authentik/POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: authentik-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: /authentik/POSTGRES_USERNAME
    - secretKey: password
      remoteRef:
        key: /authentik/POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-backup-s3-account
  namespace: authentik
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: authentik-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: /authentik/BACKUP_S3_ACCESS_KEY
    - secretKey: secret_key
      remoteRef:
        key: /authentik/BACKUP_S3_SECRET_KEY
