apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/category: infrastructure
      app.kubernetes.io/environment: dev

resources:
  - ../../base/security
  - ../../base/databases
  - ../../base/observability
  - ../../base/platform
  - ../../base/networking
  - ../../base/storage

patches:
  - target:
      kind: Secret
      name: secrets
    path: ./secrets.sops.yaml
  - target:
      kind: Kustomization
      name: external-secrets-store
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/overlays/dev/security/external-secrets/store
