apiVersion: v1
kind: Secret
metadata:
  name: secrets
stringData:
  INTERNAL_DOMAIN: ENC[AES256_GCM,data:GGOg8y/iflleqJAdUNlIe44AlOg=,iv:GwDdnnc8G3ThVh7VQUbq5atbA5czc+P8rrrzHbkDoc0=,tag:5B/CTlNVtWnue9KivPa/yw==,type:str]
  EXTERNAL_DOMAIN: ENC[AES256_GCM,data:IVzH67nKmXCsX2zBBks=,iv:4psshFgGy2HdTgguKyK1jTq6405Yj3WnRd8N27l9ZAM=,tag:RIyM9cmjo6csGLr3huJw8A==,type:str]
sops:
  age:
    - recipient: age1usemhw8v2nnr5nuxddrc7gsy3525hhv0na4hk2ur7tjara5cp90s7cpeen
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRzZZM1BlYVNpVzBpbkpx
        ZVA4S0JoME0rQ09Mdklrb0d2RmRXNVU4eEE0Cm9QTTB0aTFYRmNzdEJxc2psL3h2
        cExZUGM1TEhYNFgxemVwbUx4MEVBcVEKLS0tIFVZYjJ5a3NUWVJsUFBNNFQvUkNv
        bUVFWlloRmlSblF5ZTBHZ1NicDRQUGcK/43MW8vYleVNE8EzLse2dF1dnZvUPgyS
        QeNnp5T03Gv+tK7oMxxVjwaXodqpf1JqqhO1nFCs29dgIrD3hJzamQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-01T23:46:05Z"
  mac: ENC[AES256_GCM,data:WXqh7kDQfL1PJkTR3A+Xi6X3xi0ZrVNfzmMdJcMABF4yDb8iXbg08EhYYbaRV8ZWCR9Y6drZzA9/X9jfu435SO3rO8c7nGgT1hLG7Nf6IwgTQhClccjd3FlFlwyQDK+RHvvSiK9m6lnb8thfpaUNHi/rTz/lrBvm4SaoRBGkRxY=,iv:EElmv4jc9UKfFPv3mhgxwNxsHez/ZdMeYZ+KIvHbZpc=,tag:FdXwg2HS0vESHR6qNXe91Q==,type:str]
  encrypted_regex: ^(data|stringData|crt|key|token|secretboxencryptionsecret|bootstraptoken|secret|id)$
  version: 3.12.2
