apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: searxng-dragonfly
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  image: ghcr.io/dragonflydb/dragonfly:v2.0.0@sha256:7426fdb31ddcf7bd9499b4205f36ebaa83b26149ba1609a0d5f8f474b3631233
  replicas: 2
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: searxng-dragonfly
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
  authentication:
    passwordFromSecret:
      name: searxng-dragonfly-credentials
      key: DRAGONFLY_PASSWORD
  resources:
    requests:
      cpu: 15m
      memory: 32Mi
    limits:
      memory: 512Mi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: &app searxng-dragonfly
  labels:
    group: dragonfly
    app: *app
spec:
  selector:
    matchLabels:
      app: *app
  podTargetLabels:
    - app
  podMetricsEndpoints:
    - port: admin
