apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secret-env
  namespace: searxng
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: searxng-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SEARXNG_SECRET: "{{ .token }}"
        SEARXNG_VALKEY_URL: "valkey://:{{.password}}@dragonfly.dragonfly.svc.cluster.local:6379/11"
  data:
    - secretKey: token
      remoteRef:
        key: /searxng/SECRET_TOKEN
    - secretKey: password
      remoteRef:
        key: /dragonfly/DRAGONFLY_PASSWORD
