services:
  dockhand:
    container_name: dockhand
    image: fnsys/dockhand:v1.0.20@sha256:99f05818ef535cbbb59e53e5efd0687dac2c5fa118f673085f0441ba0d027563
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/app/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockhand.rule=Host(`dockhand.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.dockhand.entrypoints=websecure"
      - "traefik.http.routers.dockhand.tls.certresolver=letsencrypt"
      - "traefik.http.services.dockhand.loadbalancer.server.port=3000"
      - "traefik.http.services.dockhand.loadbalancer.server.scheme=http"

volumes:
  data:

networks:
  proxy:
    external: true
