apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  values:
    core:
      replicas: 1
    jobservice:
      replicas: 1
    registry:
      replicas: 1
    expose:
      type: route
      tls:
        enabled: false
      route:
        parentRefs:
          - name: envoy-internal
            namespace: envoy
        hosts:
          - harbor.${INTERNAL_DOMAIN}
