apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbor

labels:
  - pairs:
      app.kubernetes.io/module: harbor

resources:
  - ../../../base/harbor

patches:
  - path: helm.yaml
    target:
      kind: HelmRelease
  - path: pgcluster.yaml
    target:
      kind: Cluster
  - target:
      kind: ObjectBucketClaim
    patch: |-
      - op: replace
        path: /spec/additionalConfig/maxSize
        value: 1G
