apiVersion: v1
kind: Service
metadata:
  name: rustfs
spec:
  ports:
    - name: https
      port: 30293
      protocol: TCP
      targetPort: 30293
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: rustfs
subsets:
  - addresses:
      - ip: 192.168.30.20
    ports:
      - name: https
        port: 30293
        protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: rustfs
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: rustfs
      sectionName: https
  validation:
    hostname: truenas.${INTERNAL_DOMAIN}
    wellKnownCACertificates: System
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rustfs
spec:
  hostnames:
    - rustfs.intra.dreadster3.com
  parentRefs:
    - name: envoy-internal
      namespace: envoy
  rules:
    - backendRefs:
        - name: rustfs
          port: 30293
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
