apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-instance
spec:
  chartRef:
    kind: OCIRepository
    name: flux-instance
  interval: 1h
  values:
    instance:
      distribution:
        version: "2.x"
        registry: "ghcr.io/fluxcd"
      components:
        - source-controller
        - kustomize-controller
        - helm-controller
        - notification-controller
        - source-watcher
      cluster:
        type: kubernetes
        size: small
        networkPolicy: true
        multitenant: false
        domain: "cluster.local"
      sync:
        interval: 1m
        kind: GitRepository
        path: kubernetes/clusters/dev
        pullSecret: flux-system
        ref: refs/heads/feature/gateway_api
        url: https://github.com/dreadster3/home-ops
      kustomize:
        patches:
          - # Flux near OOM detection for Helm
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --feature-gates=OOMWatch=true
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --oom-watch-memory-threshold=95
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --oom-watch-interval=500ms
            target:
              kind: Deployment
              name: helm-controller
          - # Controller-level SOPS decryption
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --sops-age-secret=sops-age
            target:
              kind: Deployment
              name: kustomize-controller
          - # Watch configmaps and secrets attached to HelmReleases and Kustomizations
            patch: |-
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --watch-configs-label-selector=owner!=helm
            target:
              kind: Deployment
              name: (helm-controller|kustomize-controller)
