apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-postgres
  namespace: netbox
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: netbox-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: /netbox/POSTGRES_USERNAME
    - secretKey: password
      remoteRef:
        key: /netbox/POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-dragonfly
  namespace: netbox
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: netbox-dragonfly-credentials
    creationPolicy: Owner
  data:
    - secretKey: DRAGONFLY_PASSWORD
      remoteRef:
        key: /netbox/DRAGONFLY_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-superuser
  namespace: netbox
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: netbox-superuser
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: admin
        email: no-reply@${EXTERNAL_DOMAIN}
        api_token: "{{ .api_token }}"
        password: "{{ .password }}"
  data:
    - secretKey: api_token
      remoteRef:
        key: /netbox/ADMIN_API_TOKEN
    - secretKey: password
      remoteRef:
        key: /netbox/ADMIN_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-server
  namespace: netbox
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: netbox-server
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: /netbox/SECRET_KEY
    - secretKey: username
      remoteRef:
        key: /netbox/ADMIN_USERNAME
    - secretKey: password
      remoteRef:
        key: /netbox/ADMIN_PASSWORD
    - secretKey: api_token
      remoteRef:
        key: /netbox/ADMIN_API_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-operator
  namespace: netbox
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: netbox-operator
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: /netbox/OPERATOR_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-backup-s3-account
  namespace: netbox
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: netbox-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: /netbox/BACKUP_S3_ACCESS_KEY
    - secretKey: secret_key
      remoteRef:
        key: /netbox/BACKUP_S3_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-oidc
  namespace: netbox
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: netbox-oidc
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: /netbox/OIDC_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: /netbox/OIDC_CLIENT_SECRET
