services:
  netbird:
    image: ghcr.io/netbirdio/netbird:0.75.0@sha256:f186c12860d0d0a695a9db29bb32dfe81d8e6fb9d219364020f72c606972acc4
    restart: unless-stopped
    container_name: netbird
    hostname: vpn
    env_file: netbird.env
    environment:
      NB_MANAGEMENT_URL: https://netbird.${EXTERNAL_DOMAIN}
    volumes:
      - /var/log/docker/netbird:/var/log/netbird
    cap_add:
      - NET_ADMIN
      - NET_RAW
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    networks:
      - netbird

networks:
  netbird:
    name: netbird
    driver: bridge
