services:
  netbird:
    image: ghcr.io/netbirdio/netbird:0.76.2@sha256:597a57aaf7d92de724996ccd887c2090eda6eccdf733955eb7986ebb652a2560
    restart: unless-stopped
    container_name: netbird
    hostname: vpn
    env_file: netbird.env
    environment:
      NB_MANAGEMENT_URL: https://netbird.${EXTERNAL_DOMAIN}
    volumes:
      - /var/log/docker/netbird:/var/log/netbird
    cap_add:
      - NET_ADMIN
      - NET_RAW
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    networks:
      - netbird

networks:
  netbird:
    name: netbird
    driver: bridge
