state_dir /tmp/state
runtime_dir /tmp/run

openmetrics tcp://0.0.0.0:{env:SERVER_METRICS_PORT} { }

tls off
hostname {env:SERVER_HOSTNAME}

smtp tcp://0.0.0.0:{env:SERVER_SMTP_PORT} {
    default_source {
        deliver_to &remote_queue
    }
}

target.queue remote_queue {
    target &remote_smtp
}

target.smtp remote_smtp {
    auth plain {env:SMTP_RELAY_USERNAME} {env:SMTP_RELAY_PASSWORD}
    targets tls://{env:SMTP_RELAY_HOSTNAME}:{env:SMTP_RELAY_PORT}
}
