services:
  appraise:
    container_name: appraise
    image: caronc/apprise:v1.3.3@sha256:4bfeac268ba87b8e08e308c9aa0182fe99e9501ec464027afc333d1634e65977
    restart: unless-stopped
    environment:
      APPRISE_STATEFUL_MODE: simple
      APPRISE_WORKER_COUNT: 1
      APPRISE_ADMIN: y
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.appraise.rule=Host(`appraise.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.appraise.entrypoints=websecure"
      - "traefik.http.routers.appraise.tls.certresolver=letsencrypt"
      - "traefik.http.services.appraise.loadbalancer.server.port=8000"
    security_opt:
      - no-new-privileges:true
    volumes:
      - config:/config
      - plugins:/plugin
      - attachments:/attach
    networks:
      - proxy

volumes:
  config:
    driver: local
  plugins:
    driver: local
  attachments:
    driver: local

networks:
  proxy:
    external: true
