apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: backup-store
  namespace: joplin
spec:
  configuration:
    destinationPath: s3://joplin-cluster
    endpointURL: http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local
    s3Credentials:
      accessKeyId:
        name: joplin-cluster-bucket
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: joplin-cluster-bucket
        key: AWS_SECRET_ACCESS_KEY
