apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openwebui
  namespace: openwebui
spec:
  values:
    controllers:
      main:
        containers:
          main:
            env:
              - name: ENABLE_LOGIN_FORM
                value: "true"
              - name: OPENID_PROVIDER_URL
                value: null
              - name: OPENID_REDIRECT_URI
                value: null
              - name: OAUTH_PROVIDER_NAME
                value: null
              - name: OAUTH_SCOPES
                value: null
              - name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
                value: null
              - name: ENABLE_OAUTH_SIGNUP
                value: null
