apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openwebui

labels:
  - pairs:
      app.kubernetes.io/module: openwebui

resources:
  - ../../../base/openwebui
  - bucket.yaml

patches:
  - path: store.yaml
    target:
      kind: ObjectStore
