apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openwebui

labels:
  - pairs:
      app.kubernetes.io/module: openwebui

resources:
  - ../../../base/openwebui
  - bucket.yaml

patches:
  - path: store.yaml
    target:
      kind: ObjectStore
  - path: pgcluster.yaml
    target:
      kind: Cluster
  - patch: |-
      - op: remove
        path: /spec/values/controllers/main/containers/main/env/4
      - op: remove
        path: /spec/values/controllers/main/containers/main/env/5
      - op: remove
        path: /spec/values/controllers/main/containers/main/env/6
      - op: remove
        path: /spec/values/controllers/main/containers/main/env/7
      - op: remove
        path: /spec/values/controllers/main/containers/main/env/8
      - op: remove
        path: /spec/values/controllers/main/containers/main/env/9
      - op: remove
        path: /spec/values/controllers/main/containers/main/env/10
    target:
      kind: HelmRelease
  - patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/16
        value: https://truenas.${HOME_DOMAIN}:30292
    target:
      kind: Cronjob
