apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: openwebui-cluster
  namespace: openwebui
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "disabled"
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18-0.8.2

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  bootstrap:
    recovery: null
    initdb:
      database: openwebui
      owner: openwebui
      secret:
        name: openwebui-cluster-credentials
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vchord" CASCADE;
