apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs
  namespace: monitoring
spec:
  interval: 24h
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-single
  ref:
    tag: "0.13.9"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
  namespace: monitoring
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: victoria-logs
  values:
    server:
      fullnameOverride: victoria-logs
      retentionPeriod: "30d"
      retentionMaxDiskUsagePercent: 85

      persistentVolume:
        enabled: true
        size: 50Gi
        storageClassName: ceph-block

      resources:
        requests:
          cpu: 150m
          memory: &memory 1.5Gi
        limits:
          memory: *memory

      serviceMonitor:
        enabled: true
