apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs
  namespace: monitoring
spec:
  interval: 24h
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-single
  ref:
    semver: 0.x
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
  namespace: monitoring
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: victoria-logs
  values:
    fullnameOverride: victoria-logs-single

    server:
      retentionPeriod: "30d"

      persistentVolume:
        enabled: true
        size: 20Gi
        storageClassName: ceph-block

      resources:
        requests:
          cpu: 150m
          memory: &memory 500Mi
        limits:
          memory: *memory

      serviceMonitor:
        enabled: true
