apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sure
  namespace: sure
spec:
  values:
    web:
      replicas: 1
      resources:
        requests:
          cpu: 0m
          memory: 0Mi
    worker:
      replicas: 1
      resources:
        requests:
          cpu: 0m
          memory: 0Mi
    rails:
      extraEnv:
        APP_DOMAIN: "sure.${INTERNAL_DOMAIN}"
        WEBAUTHN_RP_ID: "${INTERNAL_DOMAIN}"
        WEBAUTHN_ALLOWED_ORIGINS: "https://sure.${INTERNAL_DOMAIN}"
        RAILS_FORCE_SSL: "false"
        RAILS_ASSUME_SSL: "false"