apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sure

labels:
  - pairs:
      app.kubernetes.io/module: sure

resources:
  - ../../../base/sure
  - bucket.yaml

patches:
  - path: helm.yaml
    target:
      kind: HelmRelease
  - path: pgcluster.yaml
    target:
      kind: Cluster
  - path: store.yaml
    target:
      kind: ObjectStore
  - path: secrets.yaml
    target:
      kind: ExternalSecret
      name: sure-backup-s3-account
  - path: network.yaml
    target:
      kind: CiliumNetworkPolicy
      name: sure-web