api:
  dashboard: true
  insecure: true

providers:
  http:
    endpoint: http://pangolin:3001/api/v1/traefik-config
    pollInterval: 5s
  docker:
    exposedByDefault: false
    network: proxy
  file:
    filename: /etc/traefik/traefik-dynamic.yaml

experimental:
  plugins:
    badger:
      moduleName: github.com/fosrl/badger
      # renovate: datasource=github-releases depName=fosrl/badger
      version: v1.7.0
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      # renovate: datasource=github-releases depName=maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.7.1
    geoblock:
      moduleName: github.com/PascalMinder/geoblock
      # renovate: datasource=github-releases depName=PascalMinder/geoblock
      version: v0.3.8

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
      middlewares:
        - security-headers@file
        - crowdsec@file
  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: "0"
        idleTimeout: "0"
        writeTimeout: "0"
    http:
      middlewares:
        - security-headers@file
        - crowdsec@file
      tls:
        certResolver: "letsencrypt"
      encodedCharacters:
        allowEncodedSlash: true
        allowEncodedQuestionMark: true
  tcp-25565:
    address: ":25565/tcp"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "afonso.antunes@live.com.pt"
      storage: "/letsencrypt/acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare # or your DNS provider
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

log:
  filePath: /var/log/traefik/traefik.log
  format: json
  level: DEBUG

accessLog:
  filePath: /var/log/traefik/access.log
  format: json

serversTransport:
  insecureSkipVerify: true
  forwardingTimeouts:
    responseHeaderTimeout: 0s
    idleConnTimeout: 0s

ping:
  entryPoint: "web"
