apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
  namespace: searxng
spec:
  values:
    controllers:
      main:
        replicas: 1
        containers:
          main:
            resources:
              requests:
                cpu: 0m
                memory: 0Mi
