apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: searxng

labels:
  - pairs:
      app.kubernetes.io/module: searxng

resources:
  - ../../../base/searxng

patches:
  - path: helm.yaml
    target:
      kind: HelmRelease
