services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:2.10.0@sha256:4d9abedcd57a9aa4d36ffb8fc9a4801aea2d295bf6ad349e23dd4b45661a5e42
    container_name: stirling-pdf
    restart: unless-stopped
    environment:
      SECURITY_ENABLELOGIN: false
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stifling.rule=Host(`stirling.${INTERNAL_DOMAIN}`) || Host(`pdf.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.stifling.entrypoints=websecure"
      - "traefik.http.routers.stifling.tls.certresolver=letsencrypt"
      - "traefik.http.services.stifling.loadbalancer.server.port=8080"
      - "traefik.http.services.stifling.loadbalancer.server.scheme=http"
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: &memory 1.5G
        limits:
          memory: *memory
    networks:
      - proxy
    volumes:
      - data:/configs

networks:
  proxy:
    external: true

volumes:
  data:
    driver: local
