---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: renovate-operator

resources:
  - secrets.yaml
  - renovatejob.yaml

configMapGenerator:
  - name: renovate-config
    options:
      disableNameSuffixHash: true
    files:
      - resources/config.json
