apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rook-ceph-operator
  namespace: &namespace rook-ceph
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/module: rook
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
  path: ./kubernetes/infrastructure/base/storage/rook/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: prometheus-operator
      namespace: monitoring
  interval: 1h
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rook-ceph-cluster
  namespace: &namespace rook-ceph
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/module: rook
  path: ./kubernetes/infrastructure/base/storage/rook/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: rook-ceph-operator
      namespace: rook-ceph
    - name: cert-manager
      namespace: cert-manager
  interval: 1h
  timeout: 5m
