apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../base/databases/qdrant/app

patches:
  - target:
      kind: HelmRelease
      name: qdrant
    patch: |-
      - op: remove
        path: /spec/values/snapshotPersistence/storageClassName
