services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15.3.0@sha256:93bbd593e07bab98d02807a28770ac87ab6c48818e319e68c1f66561feb99876
    restart: unless-stopped
    container_name: wg-easy
    network_mode: "host"
    environment:
      DISABLE_IPV6: true
    volumes:
      - /opt/docker/wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
  litestream:
    image: litestream/litestream:0.5.15-scratch@sha256:de6483d5652e67ddb23861fd4e94cdbb5f22895f0739589f49fbb047367555b2
    restart: unless-stopped
    container_name: wg-easy-litestream
    command: replicate
    env_file:
      - ./litestream.env
    volumes:
      - /opt/docker/wireguard:/data
      - ./litestream.yml:/etc/litestream.yml:ro
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
