access-key-id: ENC[AES256_GCM,data:70fTljx+5bRwT2wA/BteuSCJO7c=,iv:x+TK9dhPcumHfO/MH4R5ZXX5ghy77i2bMRKUWCunKpU=,tag:njWeCjgmiCRaOOVmVswYGg==,type:str]
secret-access-key: ENC[AES256_GCM,data:DPiVrQQa8Bvns4WTyfJnauHNB3PzyGiYV/iCNIVA4398VVmY7ftnBQ==,iv:QCA1y8MyZ/pUyUNKo37UG+dmYJsT5xU/WT+lwhGP3Uk=,tag:ssV6MkUXhrcswIWmgaQSgg==,type:str]
dbs:
    - path: /data/wg-easy.db
      replica:
        url: ENC[AES256_GCM,data:fdydy88BXnyVkLb+O1d2M0fxwqL9i7DeXnj7FsClfYIlBLoa0h6oXQSqRYgOIX+WMA==,iv:kBQ3zsr56t7SUj7Fnlr9w7W1oZr85reeJjfi5uYr4yk=,tag:Uqv1hyVKJFSXf2FRZgViLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6N281b0hhQkFDcUNZbGt4
            cDB6UUUwRmlaQ3gzWFpGZXg0bDlLejNneng0CmlNSEhIRXZkMVNmU1VYUUdsNnlk
            M1RXZW1KTEVhalFqSDB4L1NZTktZTm8KLS0tIHA2bUhURGtRNXBPR3pXclZFMDlr
            MEd0WWpNOXp1M056Y0JLbWdVSjNDZUEKvdrNrY2LYiLhl4M0AHj6q54byqpGEvmz
            8Ksj5WUZsssbWmFemgvbMU2wiPzN8WmmSjza4LktPK3CMUWBKDX7Yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1usemhw8v2nnr5nuxddrc7gsy3525hhv0na4hk2ur7tjara5cp90s7cpeen
    encrypted_regex: ^(access-key-id|secret-access-key|url)$
    lastmodified: "2026-08-04T22:21:34Z"
    mac: ENC[AES256_GCM,data:1PdBJgalvvtqzWWnOPKkk+vMNOq5nSC9FnUCOxxxNdMsd6iiuJ/8d4p3FBwpER41LE7yr9mX3SxrMD/v77D0p/HIpgIN5s5yL0xKHvLzQ0W/CRcU88l7hpG53v+d59cZhS36bN/3giUgep4dN4LX2NXjSU7+aOJ5QyOk92PUNJ8=,iv:1T6NclTS2iRukYwqk8mHmw5vFQPDmXPDE4tpqby2PmU=,tag:ih/c+bEtS9AGbU9MFKraHQ==,type:str]
    version: 3.13.3
