services:
  newt:
    image: fosrl/newt:1.17.0@sha256:3465d85200cceb0f46dad8e63a40b69ec043a81df66ed0c514714302e9b83dde
    container_name: minecraft-newt
    restart: unless-stopped
    env_file:
      - newt.env
    networks:
      - edge
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true

networks:
  edge:
    name: edge
