apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: termix

labels:
  - pairs:
      app.kubernetes.io/module: termix

resources:
  - ../../../base/termix

patches:
  - path: helm.yaml
    target:
      kind: HelmRelease
