apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-secrets
  namespace: *app
spec:
  targetNamespace: *app
  commonMetadata:
    labels:
      app.kubernetes.io/module: *app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *app
  path: ./kubernetes/infrastructure/base/security/external-secrets/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: prometheus-operator
      namespace: monitoring
  interval: 1h
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app vault-store
  namespace: &namespace external-secrets
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/module: *namespace
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *app
  path: ./kubernetes/infrastructure/base/security/external-secrets/store
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: *namespace
      namespace: *namespace
    - name: vault
      namespace: vault
  interval: 1h
  timeout: 5m
