authentik_cliend_id: ENC[AES256_GCM,data:xDO5zbc2/Y89r4HFCgs/zvcaxOKkLuJms0ME6QzcPhgrjxsibnih9w==,iv:xLYJ4Zm8UMTiRvg0DSLAw9092CKC6YEKKnkINl5f6UA=,tag:gOqvo6rVTO14FKv7RFUh3w==,type:str]
authentik_client_secret: ENC[AES256_GCM,data:Fbbmv+XYdBn2wGqxSy3tRK6AqdXwukcihDCW4+HiPz/Flcdk9RqvWCwZMTIf/NuhQFrmIWtdAYmyRkdqmNU5313QDJ0Hc0PgWKSpzpNCoStGG7MpqBbEUxjI1gS+QXpWaWau5J1cX4MMvODxRz48gx+/TQhGrBBBNSe1WwVroWw=,iv:AuTWn8pcsLC8Dd+tz6Vbk0J8eooEjfAS0wNgcWcp4eI=,tag:9IJ1yW5ezKx2sjIk2x5GYw==,type:str]
authentik_configure_url: ENC[AES256_GCM,data:EQCJ+Tn4iRakAlGBe40C3P2XiIgEpz8qkOVxV358JhGbVTB0MTp9/oIbRXOp4uZazrUcyqFqEx3ZYRhtDs0TxLrLumFBRIqGrN/iayCaknSdw4rOekeiNnVihOJ6ulGMNDLVGg==,iv:kcE4vQ00Y+W3BSadSRNdYtPDkrLZUuKx2TJrsf07Wkc=,tag:7KpKkZLORx42Cu6A4fhmmw==,type:str]
sops:
    age:
        - recipient: age1usemhw8v2nnr5nuxddrc7gsy3525hhv0na4hk2ur7tjara5cp90s7cpeen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaUhVUVlaYmt4RmFUTlJz
            TzhaT3l2S0RNOU5oR0p5dFQrZk1yd21KRG53CkJwWTZDN2xMaE8vRnhIRmVYOExN
            RWsyKzJ3VWcyeVBrSVRES2VwUXZJOVUKLS0tIDB1YmdtVm1vWUU2TnUxVCtWSzU3
            Z0tCZDU0clRZaldhY0FLYjNyVUxIcTQKKrtbPJucm+tVAUJXbyf8HCnlQwXCCm1H
            yRc/XraIAVDwsEn/vUBQWC+tMPtJ0ElfrMLyugw8miCCO/tv6TKltQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T18:50:18Z"
    mac: ENC[AES256_GCM,data:nEexyWY1nZRgdUj/51BHFuOR0qrRmprRrWbhzR4bAHzgYlp183ovhX6FnMa+oCN6Cp0kF0NwjYjLGaHsUFwxhPR84mmXspKb/bvtot1nBLmfOctvGhuX/4/BGyJYSxKBpLjkL7Vx3b8cAH1SgwyqTbeHWg8VrDNUP4q3BdnPvFM=,iv:xGHb7mz4ELx8GjbdVM1pi2JzeDJZDzzNH77dcI0Vc3M=,tag:1cdhF+WqHUSyYvgrz0JVtA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
