apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: termix
  namespace: termix
spec:
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: app-template
      version: 4.6.x
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/lukegus/termix
              tag: release-2.1.0@sha256:52e45c1ea3fb85be5b3ade5ff42eed0946fe81131cbd834f6960e00797f17f86
            env:
              TZ: Europe/Lisbon
              PORT: &port 8080
            ports:
              - containerPort: *port
                name: http
                protocol: TCP
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                cpu: 100m
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              # Needs to be false for nginx files to work
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault

    service:
      main:
        controller: main
        annotations:
          netbird.io/expose: "true"
        ports:
          http:
            port: 80
            targetPort: http

    route:
      main:
        hostnames:
          - termix.${INTERNAL_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: envoy
        rules:
          - backendRefs:
              - identifier: main
                port: http

    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: ceph-block
        size: 1Gi
        globalMounts:
          - path: /app/data
