services:
  bootstrap:
    image: busybox:latest
    container_name: home-assistant-bootstrap
    command:
      - sh
      - -c
      - |
        cp -vr /config/* /homeassistant
        touch /homeassistant/scenes.yaml
        touch /homeassistant/automations.yaml
        touch /homeassistant/scripts.yaml
        echo "Configuration files copied successfully"
    volumes:
      - ./config:/config
      - /opt/docker/home-assistant/config:/homeassistant
    networks: []

  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:2026.3.2@sha256:572a5d030f652e9ef6c6d4f6631169af83eb3b739c9b4b3965669f5e9d9f3858
    restart: unless-stopped
    depends_on:
      bootstrap:
        condition: service_completed_successfully
    environment:
      TZ: Europe/Lisbon
    volumes:
      - /opt/docker/home-assistant/config:/config
      - /opt/docker/home-assistant/backups:/config/backups
      - /run/dbus:/run/dbus:ro
      # Editor files
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls.certresolver=letsencrypt"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
    networks:
      - proxy

networks:
  proxy:
    external: true
