services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:2026.3.1@sha256:0e091dfce3068339c3e1d14382e6c34141e05cd589a1972ebd4d9a8e6b5d8969
    restart: unless-stopped
    environment:
      TZ: Europe/Lisbon
    volumes:
      - /opt/docker/home-assistant/config:/config
      - ./config/configuration.yaml:/config/configuration.yaml
      - ./config/scripts:/config/scripts
      - ./config/scenes:/config/scenes
      - ./config/themes:/config/themes
      - ./config/automations:/config/automations
      - ./config/integrations:/config/integrations
      - /opt/docker/home-assistant/backups:/config/backups
      - /run/dbus:/run/dbus:ro
      # Editor files
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls.certresolver=letsencrypt"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
    networks:
      - proxy

networks:
  proxy:
    external: true
