apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: openwebui-cluster
  namespace: openwebui
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.9-standard-trixie
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: ceph-block
    size: 5Gi

  bootstrap:
    recovery:
      source: backup
      database: openwebui
      owner: openwebui
      secret:
        name: openwebui-cluster-credentials
    # initdb:
    #   database: openwebui
    #   owner: openwebui
    #   secret:
    #     name: openwebui-cluster-credentials

  externalClusters:
    - name: backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: backup-store
          serverName: openwebui-cluster

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backup-store

  resources:
    requests:
      cpu: 50m
      memory: &memory 256Mi
    limits:
      memory: *memory

  monitoring:
    enablePodMonitor: true
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: openwebui-cluster-backup
  namespace: openwebui
spec:
  cluster:
    name: openwebui-cluster
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
