apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-postgres
  namespace: openwebui
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: openwebui-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: /openwebui/POSTGRES_USERNAME
    - secretKey: password
      remoteRef:
        key: /openwebui/POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-backup-s3-account
  namespace: openwebui
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: openwebui-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: /openwebui/BACKUP_S3_ACCESS_KEY
    - secretKey: secret_key
      remoteRef:
        key: /openwebui/BACKUP_S3_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-redis
  namespace: openwebui
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: openwebui-redis-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: /openwebui/REDIS_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-secret-env
  namespace: openwebui
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: openwebui-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: postgresql://{{ .pg_username }}:{{ .pg_password }}@openwebui-cluster-rw:5432/openwebui
        REDIS_URL: redis://:{{.redis_password}}@mymaster:6379/0
        WEBSOCKET_REDIS_URL: redis://:{{.redis_password}}@mymaster:6379/1
        WEBUI_SECRET_KEY: "{{ .token }}"
        OAUTH_CLIENT_ID: "{{ .client_id }}"
        OAUTH_CLIENT_SECRET: "{{ .client_secret }}"
  data:
    - secretKey: pg_username
      remoteRef:
        key: /openwebui/POSTGRES_USERNAME
    - secretKey: pg_password
      remoteRef:
        key: /openwebui/POSTGRES_PASSWORD
    - secretKey: redis_password
      remoteRef:
        key: /openwebui/REDIS_PASSWORD
    - secretKey: token
      remoteRef:
        key: /openwebui/SECRET_TOKEN
    - secretKey: client_id
      remoteRef:
        key: /openwebui/OIDC_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: /openwebui/OIDC_CLIENT_SECRET
