services:
  doco-cd:
    container_name: doco-cd
    image: ghcr.io/kimdre/doco-cd:0.71.0@sha256:e8664d066ec2d0823b1efaa93d8299ccf4ed12eb3b527990d90b412021321af3
    environment:
      HTTP_PORT: 8080
      LOG_LEVEL: debug
      POLL_CONFIG_FILE: /etc/doco-cd/poll-config.yaml
      DEPLOY_CONFIG_BASE_DIR: ./docker/mgmt
    restart: unless-stopped
    configs:
      - source: poll-config.yaml
        target: /etc/doco-cd/poll-config.yaml
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test:
        - CMD
        - /doco-cd
        - healthcheck
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3

configs:
  poll-config.yaml:
    content: |
      - url: https://github.com/dreadster3/home-ops.git
        interval: 180
        reference: refs/heads/feat/doco/mgmt

volumes:
  data:
    driver: local
