apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime
  namespace: uptime
spec:
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: app-template
      version: 4.6.x
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/louislam/uptime-kuma
              tag: 2.2.1@sha256:7337368a77873f159435de9ef09567f68c31285ed5f951dec36256c4b267ee44
            env:
              TZ: Europe/Lisbon
              UPTIME_KUMA_DB_TYPE: sqlite
            ports:
              - containerPort: 3001
                name: http
                protocol: TCP
            resources:
              requests:
                cpu: 70m
                memory: 256Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }

    service:
      main:
        controller: main
        ports:
          http:
            port: 80
            targetPort: http

    route:
      main:
        hostnames:
          - uptime.${INTERNAL_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: envoy
        rules:
          - backendRefs:
              - identifier: main
                port: http

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteMany
        storageClass: ceph-filesystem
        size: 3Gi
        globalMounts:
          - path: /app/data
