apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: uptime-backup-credentials
  namespace: uptime
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: uptime-backup-s3-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials: |
          [default]
          aws_access_key_id = {{ .access_key }}
          aws_secret_access_key = {{ .secret_key }}
        config: |
          [default]
          skip_verify = false
  data:
    - secretKey: access_key
      remoteRef:
        key: /uptime/BACKUP_S3_ACCESS_KEY
    - secretKey: secret_key
      remoteRef:
        key: /uptime/BACKUP_S3_SECRET_KEY
