apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dragonfly
  namespace: dragonfly
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: dragonfly-credentials
    creationPolicy: Owner
  data:
    - secretKey: DRAGONFLY_PASSWORD
      remoteRef:
        key: /dragonfly/DRAGONFLY_PASSWORD