apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qdrant-secret
  namespace: qdrant
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: qdrant-apikey
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: /qdrant/API_KEY
