apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: harbor-dragonfly
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.38.0@sha256:243bf004df5e137d9432c35367d7c86e6d2b5bcb6700be4b6397fcb9306b794b
  replicas: 2
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
  # authentication:
  #   passwordFromSecret:
  #     name: harbor-dragonfly-credentials
  #     key: REDIS_PASSWORD
  resources:
    # Real resources required
    requests:
      cpu: 15m
      memory: 50Mi
    # Minimum required to initialize due to dragonfly-operator
    limits:
      memory: 512Mi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: &app harbor-dragonfly
  labels:
    group: dragonfly
    app: *app
spec:
  selector:
    matchLabels:
      app: *app
  podTargetLabels:
    - app
  podMetricsEndpoints:
    - port: admin
