apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: harbor
  name: kubernetes-secret-store-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: harbor
  name: kubernetes-secret-store-role
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-secret-store-role-binding
  namespace: harbor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubernetes-secret-store-role
subjects:
  - kind: ServiceAccount
    name: kubernetes-secret-store-sa
    namespace: harbor
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kubernetes-secret-store
  namespace: harbor
spec:
  provider:
    kubernetes:
      remoteNamespace: harbor
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: kubernetes-secret-store-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-s3-storage
  namespace: harbor
spec:
  secretStoreRef:
    name: kubernetes-secret-store
    kind: SecretStore
  target:
    name: harbor-s3-storage
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        REGISTRY_STORAGE_S3_ACCESSKEY: "{{ .AWS_ACCESS_KEY_ID }}"
        REGISTRY_STORAGE_S3_SECRETKEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: harbor-bucket
