apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-redis
  namespace: harbor
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: harbor-redis-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        REDIS_PASSWORD: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: /harbor/REDIS_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secret-key
  namespace: harbor
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: harbor-secret-key
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secretKey: "{{ .secret_key }}"
  data:
    - secretKey: secret_key
      remoteRef:
        key: /harbor/SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core-secret
  namespace: harbor
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: harbor-core-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secret: "{{ .secret }}"
  data:
    - secretKey: secret
      remoteRef:
        key: /harbor/CORE_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core-csrf
  namespace: harbor
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: harbor-core-csrf
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CSRF_KEY: "{{ .csrf }}"
  data:
    - secretKey: csrf
      remoteRef:
        key: /harbor/CORE_CSRF
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-jobservice-secret
  namespace: harbor
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: harbor-jobservice-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secret: "{{ .secret }}"
  data:
    - secretKey: secret
      remoteRef:
        key: /harbor/JOBSERVICE_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry-secret
  namespace: harbor
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: harbor-registry-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secret: "{{ .secret }}"
  data:
    - secretKey: secret
      remoteRef:
        key: /harbor/REGISTRY_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-postgres
  namespace: harbor
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: harbor-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: /harbor/POSTGRES_USERNAME
    - secretKey: password
      remoteRef:
        key: /harbor/POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-backup-s3-account
  namespace: harbor
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: harbor-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: /harbor/BACKUP_S3_ACCESS_KEY
    - secretKey: secret_key
      remoteRef:
        key: /harbor/BACKUP_S3_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin
  namespace: harbor
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: harbor-admin-password
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HARBOR_ADMIN_PASSWORD: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: /harbor/ADMIN_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry-credentials
  namespace: harbor
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: harbor-registry-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        REGISTRY_PASSWD: "{{ .password }}"
        REGISTRY_HTPASSWD: '{{ htpasswd .username .password "bcrypt"}}'
  data:
    - secretKey: username
      remoteRef:
        key: /harbor/REGISTRY_USERNAME
    - secretKey: password
      remoteRef:
        key: /harbor/REGISTRY_PASSWORD
