apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netbox

labels:
  - pairs:
      app.kubernetes.io/module: netbox

resources:
  - ../../../base/netbox

patches:
  - path: helm.yaml
    target:
      kind: HelmRelease
  - path: pgcluster.yaml
    target:
      kind: Cluster
