---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda-http-add-on
  namespace: keda
spec:
  dependsOn:
    - name: keda
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: keda-add-ons-http
      version: 0.*
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: keda
  values:
    operator:
      replicas: 1
    scaler:
      replicas: 1
    interceptor:
      replicas:
        min: 1
        max: 3