apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cert-manager
  namespace: *app
spec:
  targetNamespace: *app
  commonMetadata:
    labels:
      app.kubernetes.io/module: *app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *app
  path: ./kubernetes/infrastructure/base/security/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cert-manager-issuers
  namespace: &namespace cert-manager
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/module: *namespace
  path: ./kubernetes/infrastructure/base/security/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 1h
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app trust-manager
  namespace: &namespace cert-manager
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/module: *namespace
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
  path: ./kubernetes/infrastructure/base/security/cert-manager/trust-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 1h
  timeout: 5m
