apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n8n

labels:
  - pairs:
      app.kubernetes.io/module: n8n

resources:
  - ../../../base/n8n
  - bucket.yaml

patches:
  - path: helm.yaml
    target:
      kind: HelmRelease
  - path: pgcluster.yaml
    target:
      kind: Cluster
  - path: store.yaml
    target:
      kind: ObjectStore
