apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-tsig-key
  namespace: external-dns
spec:
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: external-dns-tsig-key
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: TECHNITIUM_TSIG_KEY
