apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maddy-secret-env
  namespace: maddy
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: maddy-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SMTP_RELAY_HOSTNAME: "{{ .smtp_relay_hostname }}"
        SMTP_RELAY_PORT: "{{ .smtp_relay_port }}"
        SMTP_RELAY_USERNAME: "{{ .smtp_relay_username }}"
        SMTP_RELAY_PASSWORD: "{{ .smtp_relay_password }}"
  data:
    - secretKey: smtp_relay_hostname
      remoteRef:
        key: /maddy/SMTP_RELAY_HOSTNAME
    - secretKey: smtp_relay_port
      remoteRef:
        key: /maddy/SMTP_RELAY_PORT
    - secretKey: smtp_relay_username
      remoteRef:
        key: /maddy/SMTP_RELAY_USERNAME
    - secretKey: smtp_relay_password
      remoteRef:
        key: /maddy/SMTP_RELAY_PASSWORD
