apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbird-api-key
  namespace: netbird
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: netbird-api-key
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NB_API_KEY: "{{ .api_key }}"
  data:
    - secretKey: api_key
      remoteRef:
        key: /netbird/MANAGEMENT_API_KEY
