apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless

labels:
  - pairs:
      app.kubernetes.io/module: paperless

resources:
  - ../../../base/paperless

patches:
  - path: helm.yaml
    target:
      kind: HelmRelease
  - path: pgcluster.yaml
    target:
      kind: Cluster
