apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-cluster
  namespace: paperless
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "disabled"
spec:
  bootstrap:
    recovery: null
    initdb:
      database: paperless
      owner: paperless
      secret:
        name: paperless-cluster-credentials
