services:
  server:
    container_name: it-tools
    image: ghcr.io/corentinth/it-tools:2024.10.22-7ca5933@sha256:8b8128748339583ca951af03dfe02a9a4d7363f61a216226fc28030731a5a61f
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ittools.rule=Host(`ittools.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.ittools.entrypoints=websecure,web"
      - "traefik.http.routers.ittools.tls.certresolver=letsencrypt"
      - "traefik.http.services.ittools.loadbalancer.server.port=80"
