services:
  duplicati:
    container_name: duplicati
    image: duplicati/duplicati:2.3.0.0@sha256:d63ea5b2524b7e73889f3c7b9bee48690cc6dc4ae7f46f48d9c70d265e2f99ce
    restart: unless-stopped
    environment:
      DUPLICATI__WEBSERVICE_ALLOWED_HOSTNAMES: duplicati.${INTERNAL_DOMAIN}
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duplicati.rule=Host(`duplicati.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.duplicati.entrypoints=websecure"
      - "traefik.http.routers.duplicati.tls.certresolver=letsencrypt"
      - "traefik.http.services.duplicati.loadbalancer.server.port=8200"
    security_opt:
      - no-new-privileges:true
    volumes:
      - data:/data
      - omada-controller_data:/backups/omada-controller:ro
    networks:
      - proxy

volumes:
  data:
    driver: local
  omada-controller_data:
    external: true

networks:
  proxy:
    external: true
