services:
  duplicati:
    container_name: duplicati
    image: duplicati/duplicati:2.2.0.106
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duplicati.rule=Host(`duplicati.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.duplicati.entrypoints=websecure"
      - "traefik.http.routers.duplicati.tls.certresolver=letsencrypt"
      - "traefik.http.services.duplicati.loadbalancer.server.port=8200"
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy

networks:
  proxy:
    external: true
