services:
  databasus:
    container_name: databasus
    image: databasus/databasus:v3.49.0@sha256:18fd2e22f6a2ccb04e30ff0dd4805f518b1d1ef2157490c9e3841f083ef67197
    volumes:
      - /opt/docker/databasus/data:/databasus-data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.databasus.rule=Host(`databasus.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.databasus.entrypoints=websecure"
      - "traefik.http.routers.databasus.tls.certresolver=letsencrypt"
      - "traefik.http.services.databasus.loadbalancer.server.port=4005"
    networks:
      - proxy
      - database
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER

networks:
  database:
    name: database
    driver: bridge
  proxy:
    external: true
