services:
  databasus:
    container_name: databasus
    image: databasus/databasus:v3.32.2@sha256:baf5f0fa09ac0af836654d51853e4b32ea7b12e390b2f17cee1400c33ab4de5e
    volumes:
      - /opt/docker/databasus/data:/databasus-data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.databasus.rule=Host(`databasus.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.databasus.entrypoints=websecure"
      - "traefik.http.routers.databasus.tls.certresolver=letsencrypt"
      - "traefik.http.services.databasus.loadbalancer.server.port=4005"
    networks:
      - proxy
      - database
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER

networks:
  database:
    name: database
    driver: bridge
  proxy:
    external: true
