apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: app-template
      version: 4.6.x
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    # yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.2/charts/other/app-template/values.schema.json
    controllers:
      main:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/dani-garcia/vaultwarden
              tag: 1.35.7@sha256:9a8eec71f4a52411cc43edc7a50f33e9b6f62b5baca0dd95f0c6e7fd60f1a341
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Lisbon
              DATA_FOLDER: "data"
              DOMAIN: "https://vaultwarden.${EXTERNAL_DOMAIN}"
              WEB_VAULT_ENABLED: true
              ORG_GROUPS_ENABLED: true
              ORG_EVENTS_ENABLED: true
              SMTP_HOST: smtp.gmail.com
              SMTP_SECURITY: starttls
              SMTP_PORT: 587
              SMTP_FROM: no-reply@${EXTERNAL_DOMAIN}
              SMTP_FROM_NAME: Vaultwarden
              SMTP_AUTH_MECHANISM: Login
              SIGNUPS_ALLOWED: false
              SSO_ENABLED: true
              SSO_ONLY: false
              SSO_AUTHORITY: https://authentik.${EXTERNAL_DOMAIN}/application/o/vaultwarden/
              SSO_SCOPES: openid email profile offline_access
              SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION: false
              SSO_CLIENT_CACHE_EXPIRATION: "0"
              SSO_SIGNUPS_MATCH_EMAIL: true
              DISABLE_ICON_DOWNLOAD: true
              ICON_CACHE_TTL: 0
            envFrom:
              - secretRef:
                  name: vaultwarden-secret-env
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            ports:
              - containerPort: 80
                name: http
                protocol: TCP
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

    # -- Configures service settings for the chart.
    service:
      main:
        controller: main
        sessionAffinity: ClientIP
        sessionAffinityConfig:
          clientIP:
            timeoutSeconds: 10800
        ports:
          http:
            port: 80
            targetPort: http

    route:
      main:
        hostnames:
          - vaultwarden.${INTERNAL_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: envoy
        rules:
          - backendRefs:
              - identifier: main
                port: http

    # -- Configure persistence settings for the chart under this key.
    persistence:
      config:
        type: persistentVolumeClaim
        size: 5Gi
        accessMode: ReadWriteMany
        storageClass: ceph-filesystem
        globalMounts:
          - path: /data
