apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: vaultwarden-admin-token
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        TOKEN: "{{ .admin_token_hash }}"
  data:
    - secretKey: admin_token_hash
      remoteRef:
        key: /vaultwarden/ADMIN_TOKEN_HASH
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-postgres
  namespace: vaultwarden
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: vaultwarden-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: /vaultwarden/POSTGRES_USERNAME
    - secretKey: password
      remoteRef:
        key: /vaultwarden/POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-backup-s3-account
  namespace: vaultwarden
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: vaultwarden-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: /vaultwarden/BACKUP_S3_ACCESS_KEY
    - secretKey: secret_key
      remoteRef:
        key: /vaultwarden/BACKUP_S3_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-backup-s3-credentials
  namespace: vault
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: vaultwarden-backup-s3-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials: |
          [default]
          aws_access_key_id = {{ .access_key }}
          aws_secret_access_key = {{ .secret_key }}
        config: |
          [default]
          skip_verify = false
  data:
    - secretKey: access_key
      remoteRef:
        key: /vaultwarden/BACKUP_S3_ACCESS_KEY
    - secretKey: secret_key
      remoteRef:
        key: /vaultwarden/BACKUP_S3_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secret-env
  namespace: vaultwarden
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: vaultwarden-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: postgresql://{{ .pg_username }}:{{ .pg_password }}@vaultwarden-cluster-rw:5432/vaultwarden
        SMTP_USERNAME: "{{ .smtp_username }}"
        SMTP_PASSWORD: "{{ .smtp_password }}"
        SSO_CLIENT_ID: "{{ .client_id }}"
        SSO_CLIENT_SECRET: "{{ .client_secret }}"
        ADMIN_TOKEN: "{{ .admin_token_hash }}"
        YUBICO_CLIENT_ID: "{{ .yubico_client_id }}"
        YUBICO_SECRET_KEY: "{{ .yubico_secret_key }}"
  data:
    - secretKey: pg_username
      remoteRef:
        key: /vaultwarden/POSTGRES_USERNAME
    - secretKey: pg_password
      remoteRef:
        key: /vaultwarden/POSTGRES_PASSWORD
    - secretKey: smtp_username
      remoteRef:
        key: /vaultwarden/SMTP_USERNAME
    - secretKey: smtp_password
      remoteRef:
        key: /vaultwarden/SMTP_PASSWORD
    - secretKey: client_id
      remoteRef:
        key: /vaultwarden/OIDC_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: /vaultwarden/OIDC_CLIENT_SECRET
    - secretKey: admin_token_hash
      remoteRef:
        key: /vaultwarden/ADMIN_TOKEN_HASH
    - secretKey: yubico_client_id
      remoteRef:
        key: /vaultwarden/YUBICO_CLIENT_ID
    - secretKey: yubico_secret_key
      remoteRef:
        key: /vaultwarden/YUBICO_SECRET_KEY
