apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  values:
    prometheus:
      prometheusSpec:
        replicas: 1
        retention: 2d
        retentionSize: 5GB
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
        thanos:
          resources:
            requests:
              cpu: 5m
              memory: 64Mi
            limits:
              memory: 128Mi
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 10Gi
    alertmanager:
      alertmanagerSpec:
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            memory: 64Mi
