apiVersion: v1
kind: Secret
metadata:
  name: infisical-credentials
stringData:
  clientId: ENC[AES256_GCM,data:sXSNIgOfuy8yJoWNtd/mcheL9ImyGOGq0LVCgl1IpIta5wpc,iv:S0ZC+FuSMp+YOUEGCcPCridnYDEp+2pGapUNcjLyPpo=,tag:vh//31y66X3sA0/pfWhFqQ==,type:str]
  clientSecret: ENC[AES256_GCM,data:V3Mp9dKr1kTGsUz92K19tRCCVsL6K8QoOK58iWeR7v1ScBeJ+YpusD2gWB4rqzcyfg3p/1ot2CZhe9Yn3XEj4g==,iv:6/aZ+nQ05hJ39T1hcDU6eY8EC4aFLFHAyDEFJRnhmhE=,tag:py4mv/B+dWrq8lWnyo7fIw==,type:str]
sops:
  age:
    - recipient: age1usemhw8v2nnr5nuxddrc7gsy3525hhv0na4hk2ur7tjara5cp90s7cpeen
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwL2dCQU1VOTBqRmR3ZHUv
        M0tSZjZuMGFpejNyVE9DUGhMQ2NLTlB5ZVJJCldIYzZMMU10MjZET20rNVBmM3Qx
        aEJKdFlIdXRTbFc5blVjd1lsbUQ2KzAKLS0tIElBc1gxMWZOUDhzdnoydjNPUEl6
        ZFAyNkxiUjdVTFcwVUVsWmpLejVPNEEKBH9fYoB0ZC1MwILdt8svsepHtWw17beP
        TUa7x9J+F/ZoaIdQpkzPToHoRf5cHI/kiSIzRJ6aZot8APNmqeZ5vA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-01T00:24:07Z"
  mac: ENC[AES256_GCM,data:Xn/avJonSYTaBNLzulUlX77CE92STD1iD0y1pCSPI+oUSuS1jhmOdsEVHTgqtUvO/+bGuXeISLN37gFlkcW2tadG+1RsihzlC1lvbJwJNvlyF9D2Ny65UlJVXFXbg4dtkww+NhJpD4cUSMgW04ukEQU9kS/Y+m3btsRGDCvLkYA=,iv:WMNba2606LAe4wXzN9aqqrPz1frYOjemvHAFRH6gLZ0=,tag:gflg12cK5R0BIb5LxFmpKg==,type:str]
  encrypted_regex: ^(data|stringData|crt|key|token|secretboxencryptionsecret|bootstraptoken|secret|id)$
  version: 3.12.2
