apiVersion: v1
kind: Secret
metadata:
    name: infisical-credentials
stringData:
    clientId: ENC[AES256_GCM,data:85qxZQ1yrwBQPmDGY6DnP6Ddf3pC3UzqJMbUItt17SBYhuwl,iv:DGAcAeNZkt/EpgvdADJiydi4WDsQNtiC63KRSLR6mIY=,tag:s49+KZ8U/oiybASpWnHaIw==,type:str]
    clientSecret: ENC[AES256_GCM,data:XxqnoasUB/i66aFEuoR7vkwURibFDo3viYk5opZWfhXLYqNbhRIDxUAGTkGnpGBAcaAOOrl4+5GflToMCqhE7g==,iv:cKFjSAYjzn2WFJFA8itkhmfVD8U1Rh8zpEP5lpVzjd4=,tag:wPv0qqsJws7zFDuL2rGPVQ==,type:str]
sops:
    age:
        - recipient: age1usemhw8v2nnr5nuxddrc7gsy3525hhv0na4hk2ur7tjara5cp90s7cpeen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwL2dCQU1VOTBqRmR3ZHUv
            M0tSZjZuMGFpejNyVE9DUGhMQ2NLTlB5ZVJJCldIYzZMMU10MjZET20rNVBmM3Qx
            aEJKdFlIdXRTbFc5blVjd1lsbUQ2KzAKLS0tIElBc1gxMWZOUDhzdnoydjNPUEl6
            ZFAyNkxiUjdVTFcwVUVsWmpLejVPNEEKBH9fYoB0ZC1MwILdt8svsepHtWw17beP
            TUa7x9J+F/ZoaIdQpkzPToHoRf5cHI/kiSIzRJ6aZot8APNmqeZ5vA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T19:04:14Z"
    mac: ENC[AES256_GCM,data:/SOKnsySpXd3y12+pvHXR8Ut6XgIYAcAgYhluFT2cS4cpXUEOV4W6c44EaZo9H5XT6m9RPoH5w9ygib3lwvLpKcxNhRnfES6R8VKi1V9/+KNsv1+6edm1IYoe3imOHX6X+s0gag15ArQrkjuPFTsrXaOhriIAC+4FFt9vtthqHY=,iv:57vuCXlwknDE9Xbz+fFKFot2cfUriCrfwqC3qKs/N+s=,tag:5meeg3I0ZCg5jI8l7KW8Bw==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|secretboxencryptionsecret|bootstraptoken|secret|id)$
    version: 3.12.2
