apiVersion: v1
kind: Secret
metadata:
    name: infisical-credentials
stringData:
    clientId: ENC[AES256_GCM,data:Bpd2dkfyufsFudnvKWZHddNvmIhPJy/8u6MI+5EDHa5jXGYP,iv:lwYv9XbMh2Fj1tWvYRYNd8XmOCW12LErgpWUGy4gick=,tag:Biinh0f6NJolo6KAskWCdA==,type:str]
    clientSecret: ENC[AES256_GCM,data:S+oHo2Zi0ku1d2BtkbPDh34Kj9yJt7pI34Sh8wF8mAbj8ZM7eI8QejULJetenGvYcw2zlLKAhQztReFctM8b0A==,iv:qXooeIdPBx9TBOzzV+HQpszP6gGgm03plUgmzU3Z53g=,tag:XzSqzlUyq+CgpWz/+bBtaA==,type:str]
sops:
    age:
        - recipient: age1usemhw8v2nnr5nuxddrc7gsy3525hhv0na4hk2ur7tjara5cp90s7cpeen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwL2dCQU1VOTBqRmR3ZHUv
            M0tSZjZuMGFpejNyVE9DUGhMQ2NLTlB5ZVJJCldIYzZMMU10MjZET20rNVBmM3Qx
            aEJKdFlIdXRTbFc5blVjd1lsbUQ2KzAKLS0tIElBc1gxMWZOUDhzdnoydjNPUEl6
            ZFAyNkxiUjdVTFcwVUVsWmpLejVPNEEKBH9fYoB0ZC1MwILdt8svsepHtWw17beP
            TUa7x9J+F/ZoaIdQpkzPToHoRf5cHI/kiSIzRJ6aZot8APNmqeZ5vA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T23:32:24Z"
    mac: ENC[AES256_GCM,data:1ef7VFJd+E2PujONgn/L7mz9zPwaM1zsYFveUYOp2iW9n604fLn/h0q2knJUrz0REdijQ17WwASC3yrGbBsEzlLxPAqliF1hVidHjzSsKSY3DjA1u+cYe3+Y75q6Xo6wqX50dVMWs6oebwftPQ7Pb49tqCINOw0OKlE1HFeRxtw=,iv:iKxWOgYPXRiqZQFDrXLCqunyGyNsX74+SF7Eug4ou1U=,tag:HFv7OQR/wa7JvKvhXEC/kA==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|secretboxencryptionsecret|bootstraptoken|secret|id)$
    version: 3.12.2
