apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../base/security/external-secrets/store

patches:
  - path: infiscal-credentials.yaml
    target:
      kind: Secret
      name: infisical-credentials
  - target:
      kind: ClusterSecretStore
      name: infisical
    patch: |-
      - op: replace
        path: /spec/provider/infisical/secretsScope/environmentSlug
        value: dev
