apiVersion: v1
kind: Secret
metadata:
    name: infisical-credentials
stringData:
    clientId: ENC[AES256_GCM,data:ptLx6hXDX7JqDdyyWJgsFb7QPjl4yEsvW4pGNd+O4RS5ecOs,iv:QE7LHPDfhUTvI+oqvKqTnhLdp8YW6cochkZOjfb32Xc=,tag:rt/zsZVlCHDrYDqjjonbEQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:3rHxwt8im/V9pSWt2NcVqHCoX/ryTODNcYUgtqBjs8dIHOYBshCPL5xLjmL0Gn4RFOR1Xs06NJEipYp3d1HmIw==,iv:BJP6EG/wn1HFEvrQM3XG7vh9BJlufUSvTujQBGQLWyI=,tag:K0GMy4isIu1MZXjScpKjxg==,type:str]
sops:
    age:
        - recipient: age1usemhw8v2nnr5nuxddrc7gsy3525hhv0na4hk2ur7tjara5cp90s7cpeen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVWJvVnpLMmpnWGE4MVlE
            b05mR0UreWxWTklvYWN6Q1Y4bzNiUTU2TDJrClJDWlRwMUZocUVlYU9MZ1ExZWVM
            M3B1Tjlhd1BBb3pMcWNzL3lyRFdrejQKLS0tIHBIMGs5dWZBL05xMkRPOHpFd0o0
            Sm1RVUgvbXdrdHB1b1c3dFdTNW85MUEK0PJJOy1muGooA9vYvzn6TMw7xkCjpck6
            g8+kkUHYlOrxuJ5uYkY4ez6tx0QTy+v9j8vnkFE1TB0Jz13h0R56FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T10:48:35Z"
    mac: ENC[AES256_GCM,data:4hmBJNpb2R74nQpvghhZGJhtu4r2E1zA12QbbfVRxk23HY+j3aoCbdPad/gR5XQaAnaSBI4buszWtDuaTXsuH0NBLpqHa4MQc5AtVxsajc5NdXaDiphnur0HiXPAPrtfIVcVr0mF5hlMDdpi7Qa2gRS+cmy+WzCG5Fxms9GuXSk=,iv:8Imv4Q4NRlrPN1mYCV0W+XjXeZnv88KwdEs5MY189bU=,tag:7gmIv44JNajryBhkYjpAgA==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|secretboxencryptionsecret|bootstraptoken|secret|id)$
    version: 3.12.2
