apiVersion: v1
kind: Secret
metadata:
  name: infisical-credentials
stringData:
  clientId: ENC[AES256_GCM,data:InaehGrijxhMLO7NulYyDLKUPC4agP/YbwSxRqapOzqGAe3f,iv:9fIrWNIK67B7z41RnuWlA0bCX8OLF+VXE1WJ3/ia65g=,tag:yImEaKTeuYJF7M+WiohA0A==,type:str]
  clientSecret: ENC[AES256_GCM,data:bIPzUZL+TT47+ZHMFonLYSDQJj4bELY7lu4hkrwLOCzhrnzhhCMq3e65yazs7Oy7KN5AMaUiQOaN+wvpiUqscQ==,iv:y2GJQT19uJ28NoqUrzopNqh1QEGmCXYQ9wM2SnihF0c=,tag:mkueKRnDDMTlgPsq+fVUQA==,type:str]
sops:
  age:
    - recipient: age1usemhw8v2nnr5nuxddrc7gsy3525hhv0na4hk2ur7tjara5cp90s7cpeen
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVWJvVnpLMmpnWGE4MVlE
        b05mR0UreWxWTklvYWN6Q1Y4bzNiUTU2TDJrClJDWlRwMUZocUVlYU9MZ1ExZWVM
        M3B1Tjlhd1BBb3pMcWNzL3lyRFdrejQKLS0tIHBIMGs5dWZBL05xMkRPOHpFd0o0
        Sm1RVUgvbXdrdHB1b1c3dFdTNW85MUEK0PJJOy1muGooA9vYvzn6TMw7xkCjpck6
        g8+kkUHYlOrxuJ5uYkY4ez6tx0QTy+v9j8vnkFE1TB0Jz13h0R56FA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T18:03:56Z"
  mac: ENC[AES256_GCM,data:VUQEt4N85NSx+Syfk8sUlCOv6Dv0uKuzLEuSVKY8fUS8Jj1kn4aPe0YroTREFb+j+EavEDsYf2L8AH9rw33asy9bYD0ADj02qFddVSz8Osgfbc7LutalisTEzKP0JYsI+a9ansqQxpJ10uWgg5ro11U26QX/i4eYfC2BQKkvnzU=,iv:2260QE2My4f5pV/m7KgTwY6+VlzVglY/R+P429xEZY8=,tag:G6iS8691fOG3tMGOF+A+PA==,type:str]
  encrypted_regex: ^(data|stringData|crt|key|token|secretboxencryptionsecret|bootstraptoken|secret|id)$
  version: 3.12.2
