apiVersion: v1
kind: Secret
metadata:
    name: infisical-credentials
stringData:
    clientId: ENC[AES256_GCM,data:nFcTnt1kEH5JoE1W3/00t9uJ4ZXeZfrvPI9vWg8lb3Kte+MZ,iv:OmOi0Xlu7kutKG5Ci6mp56iJWketb3QTcfcliuG2fxQ=,tag:kkqqfHufuq/iXa+4Md3dhQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:ce6KMcnaFgFvjWYKbjlr4O6CDqlpI6n0FEWmYU8JhjDjHjCjPrZz+i7Oed8N/MZ1BPtmLOsKZ108oQNWzY/VxA==,iv:h3KR9A8zhh4/AGKoEgFXEylLQ6I6coF8NM3oenh2ZSM=,tag:hOkPkvpok5J8bEo1GSWeaA==,type:str]
sops:
    age:
        - recipient: age1usemhw8v2nnr5nuxddrc7gsy3525hhv0na4hk2ur7tjara5cp90s7cpeen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVWJvVnpLMmpnWGE4MVlE
            b05mR0UreWxWTklvYWN6Q1Y4bzNiUTU2TDJrClJDWlRwMUZocUVlYU9MZ1ExZWVM
            M3B1Tjlhd1BBb3pMcWNzL3lyRFdrejQKLS0tIHBIMGs5dWZBL05xMkRPOHpFd0o0
            Sm1RVUgvbXdrdHB1b1c3dFdTNW85MUEK0PJJOy1muGooA9vYvzn6TMw7xkCjpck6
            g8+kkUHYlOrxuJ5uYkY4ez6tx0QTy+v9j8vnkFE1TB0Jz13h0R56FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T19:05:35Z"
    mac: ENC[AES256_GCM,data:dhxeEpUSMGNrshMHUBt3FXqDfJRtnZH3pyc3zKoBXMLD+z3gqgD2mx1eJAExrcBBZcXrVOaMN1FIuDan3wJ/LBiRKpt9SmARe0tNysV1RI7j2LaW5uetDeZXOr4wnr1WyXrhWtZ4CiGmjabM3kV46fAreGw/aFeymmvoAZXwxEo=,iv:2mHMNhuThuVsXFlaw31pL4H9yaaAYXc2qWJlGkd5d/I=,tag:ZMvV2u8vp23n0/1LZSIl4w==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|secretboxencryptionsecret|bootstraptoken|secret|id)$
    version: 3.12.2
