apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-cluster
  namespace: authentik
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "disabled"
spec:
  bootstrap:
    recovery: null
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-cluster-credentials
