apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app netbird-operator
  namespace: &namespace netbird
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/module: *namespace
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
  path: ./kubernetes/infrastructure/base/networking/netbird/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: external-secrets
      namespace: external-secrets
  interval: 1h
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app netbird-operator-config
  namespace: &namespace netbird
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/module: *namespace
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
  path: ./kubernetes/infrastructure/base/networking/netbird/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: netbird-operator
      namespace: netbird
  interval: 1h
  timeout: 5m
