apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-gateway
  namespace: monitoring
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: loki-gateway
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        .htpasswd: "{{ htpasswd .gateway_username .gateway_password }}"
  data:
    - secretKey: gateway_username
      remoteRef:
        key: /loki/GATEWAY_USERNAME
    - secretKey: gateway_password
      remoteRef:
        key: /loki/GATEWAY_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-auth
  namespace: monitoring
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: loki-auth
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: /loki/GATEWAY_USERNAME
    - secretKey: password
      remoteRef:
        key: /loki/GATEWAY_PASSWORD
