version: "3"

services:
  backend:
    image: infisical/infisical:v0.159.9@sha256:7ef627d2436942d06e8b9f98c4f8d31258357d1de0a3290069eb1817bc612ea1
    container_name: infisical
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SITE_URL: https://infisical.${INTERNAL_DOMAIN}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      AUTH_SECRET: ${AUTH_SECRET}
      DB_CONNECTION_URI: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      NODE_ENV: production
      TELEMETRY_ENABLED: false
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.infisical.rule=Host(`infisical.${INTERNAL_DOMAIN}`)
      - traefik.http.routers.infisical.entrypoints=websecure
      - traefik.http.routers.infisical.tls.certresolver=letsencrypt
      - traefik.http.services.infisical.loadbalancer.server.port=8080
    user: "non-root-user"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp

  redis:
    image: redis:8.6.2-alpine@sha256:1f073813b641755b70b0200da64131bbeeb4ec5b633ca67772229b49820caafa
    container_name: infisical-redis
    restart: always
    command:
      - redis-server
      - --requirepass ${REDIS_PASSWORD}
      - --appendonly "yes"
      - --maxmemory 256mb
      - --maxmemory-policy noeviction
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - default
    volumes:
      - redis_data:/data
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
    user: "999:999"
    mem_limit: 300m

  db:
    container_name: infisical-db
    image: postgres:18.3-alpine@sha256:c5739fc99d1a3278c0a2113758a2433ce29ef964b30df705094fd77dfa5da2fa
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: infisical
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: "pg_isready --username=${DB_USER} && psql --username=${DB_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - DAC_READ_SEARCH

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    internal: true
  proxy:
    external: true
