apiVersion: v1
kind: Secret
metadata:
  name: doppler-secret
stringData:
  token: ENC[AES256_GCM,data:qjcSoqcg9InXxlCBllEYkVFMcZNDd3R37htRPT2+fzoc4gz/ZfsvQOdAdzKPhbzG+Gcswf4=,iv:z2Y6bUyxROxHCCVvIIG7AOTpg+3XKY5UJD2gQbjN4r4=,tag:B3xjEtcoE9WRYFIz19uVPg==,type:str]
sops:
  age:
    - recipient: age1usemhw8v2nnr5nuxddrc7gsy3525hhv0na4hk2ur7tjara5cp90s7cpeen
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RFI5bFJ6UlZKdlhaYVhU
        NHJmemFtV29makJSNmdSU3AvVk1qWllYQTNFCnM4Rml1TWdKREZNQXZ1TElXOVZ4
        NEtuNEphZm5GR2NUNERJQUxncGc1TkUKLS0tIDUvRWV3dTEzdEs3K1h5emVRTTRQ
        aE1uUkllM0p4T0E2aTcwekFVbk54MWsK9vfcCOLMkcXCMquoQo49wutgOTsmqV3S
        zJlqXMKpDEYZTIl0Z+GTNhkbHpLsy+C9rP/4OLozRao8j8uLkwJO1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T23:34:09Z"
  mac: ENC[AES256_GCM,data:CLYjag5tSXUID32gFNv+E0qm7so9VQ7ASdvHS9n/fgopI9yRrd+mWHCmVcpC2YEBYQffWQzHS/UW9jq+Zm6MIkrEHg/NqLhXKNZlp4Wbnuyrvf38DJUgyPw1E/5Nq6WtnlGo4wZXTFQqq1tgUBhpdCPWEwiETbooKavK58JvP6o=,iv:bpPPFrPBZeGReW1Pu8v8WGqJ14UcpMes951hsPom63s=,tag:CYv8TSZMbsmts9EQQ7wLJQ==,type:str]
  encrypted_regex: ^(data|stringData|crt|key|token|secretboxencryptionsecret|bootstraptoken|secret|id)$
  version: 3.12.2
