apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: /grafana/ADMIN_USERNAME
    - secretKey: password
      remoteRef:
        key: /grafana/ADMIN_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-authentik-client
  namespace: monitoring
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: grafana-authentik-client
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: /grafana/OIDC_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: /grafana/OIDC_CLIENT_SECRET
