apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-datasources
  namespace: monitoring
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: grafana-datasources
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          grafana/datasource: "true"
      data:
        default.yaml: |
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              url: http://thanos-query-frontend:9090
              isDefault: true
              version: 1
              jsonData:
                timeInterval: 15s
            - name: Loki
              type: loki
              url: http://loki-gateway
              basicAuth: true
              basicAuthUser: {{.loki_username}}
              secureJsonData:
                basicAuthPassword: {{.loki_password}}
              version: 1
  data:
    - secretKey: loki_username
      remoteRef:
        key: /loki/GATEWAY_USERNAME
    - secretKey: loki_password
      remoteRef:
        key: /loki/GATEWAY_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: /grafana/ADMIN_USERNAME
    - secretKey: password
      remoteRef:
        key: /grafana/ADMIN_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-authentik-client
  namespace: monitoring
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: grafana-authentik-client
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: /grafana/AUTHENTIK_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: /grafana/AUTHENTIK_CLIENT_SECRET
