apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tika

labels:
  - pairs:
      app.kubernetes.io/module: tika

resources:
  - ../../../base/tika

patches:
  - patch: |-
      - op: replace
        path: /spec/values/controllers/main/replicas
        value: 1
    target:
      kind: HelmRelease
      name: tika