apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
spec:
  external:
    enable: true
  crashCollector:
    disable: true
  cephVersion:
    allowUnsupported: false
    image: quay.io/ceph/ceph:v21.1.1@sha256:83e05d630bfb7641d1d032f8cdfe1f715a158f3d283c8173d00b7e58430d3b72
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
  monitoring:
    enabled: true
    externalMgrEndpoints:
      - ip: 192.168.30.5
      - ip: 192.168.30.6
      - ip: 192.168.30.10
    externalMgrPrometheusPort: 9283
  dataDirHostPath: /var/lib/rook
