apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
spec:
  external:
    enable: true
  crashCollector:
    disable: true
  cephVersion:
    allowUnsupported: false
    image: quay.io/ceph/ceph:v21.1.0@sha256:5ff3692d2f3f4bf47ca7717de6f8f8556440ce3e15efaa680b62cb924eec0541
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
  monitoring:
    enabled: true
    externalMgrEndpoints:
      - ip: 192.168.30.5
      - ip: 192.168.30.6
      - ip: 192.168.30.10
    externalMgrPrometheusPort: 9283
  dataDirHostPath: /var/lib/rook
