apiVersion: v1
kind: Endpoints
metadata:
  name: rook-ceph-mgr-external
subsets:
  - addresses:
      - ip: 192.168.30.5
        nodeName: pve01
      - ip: 192.168.30.6
        nodeName: pve02
      - ip: 192.168.30.10
        nodeName: pve30
    ports:
      - name: http-external-metrics
        port: 9283
        protocol: TCP
