apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: monitoring
  name: kubernetes-secret-store-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: monitoring
  name: kubernetes-secret-store-role
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-secret-store-role-binding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubernetes-secret-store-role
subjects:
  - kind: ServiceAccount
    name: kubernetes-secret-store-sa
    namespace: monitoring
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kubernetes-secret-store
  namespace: monitoring
spec:
  provider:
    kubernetes:
      remoteNamespace: monitoring
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: kubernetes-secret-store-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thanos-object-store
  namespace: monitoring
spec:
  secretStoreRef:
    name: kubernetes-secret-store
    kind: SecretStore
  target:
    name: thanos-object-store
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        objstore.yml: |
          type: S3
          config:
            bucket: thanos
            endpoint: rook-ceph-rgw-k8s-ceph-objectstore.rook-ceph.svc.cluster.local
            access_key: {{.AWS_ACCESS_KEY_ID}}
            secret_key: {{.AWS_SECRET_ACCESS_KEY}}
            insecure: true
  dataFrom:
    - extract:
        key: thanos-bucket
