apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: joplin-postgres
  namespace: joplin
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: joplin-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: /joplin/POSTGRES_USERNAME
    - secretKey: password
      remoteRef:
        key: /joplin/POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: joplin-backup-s3-account
  namespace: joplin
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: joplin-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: /joplin/BACKUP_S3_ACCESS_KEY
    - secretKey: secret_key
      remoteRef:
        key: /joplin/BACKUP_S3_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: joplin-secret-env
  namespace: joplin
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: joplin-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: "{{ .username }}"
        POSTGRES_PASSWORD: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: /joplin/POSTGRES_USERNAME
    - secretKey: password
      remoteRef:
        key: /joplin/POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: joplin-saml-metadata
  namespace: joplin
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: joplin-saml-metadata
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        joplin-idp.xml: "{{ .metadata }}"
  data:
    - secretKey: metadata
      remoteRef:
        key: /joplin/SAML_METADATA
