apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: playwright
spec:
  image: mcr.microsoft.com/playwright/mcp:v0.0.78@sha256:3d871c22ea2d4cca0966e2cfb1860e1cb03eb7353725a3d6cffd133296fb04eb
  transport: stdio
  podTemplateSpec:
    spec:
      volumes:
        - name: home
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      containers:
        - name: mcp
          volumeMounts:
            - name: home
              mountPath: /home/node
            - name: tmp
              mountPath: /tmp
