apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: playwright
spec:
  image: mcr.microsoft.com/playwright/mcp:v0.0.80@sha256:dda1f7f9b812e22946635c8af7df9288b96d3b9e3f0f1b8576d6823e2031c1de
  transport: stdio
  env:
    - name: PLAYWRIGHT_MCP_ISOLATED
      value: "true"
  podTemplateSpec:
    spec:
      volumes:
        - name: home
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      containers:
        - name: mcp
          volumeMounts:
            - name: home
              mountPath: /home/node
            - name: tmp
              mountPath: /tmp
