apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: searxng
spec:
  image: docker.io/isokoliuk/mcp-searxng:1.14.0@sha256:9af77b4fa75b933ef0a3ae49f4ddf086ecceaccac5740bc595a6174b2f0d1a26
  transport: stdio
  env:
    - name: SEARXNG_URL
      value: http://searxng.searxng.svc.cluster.local
