apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: searxng
spec:
  image: docker.io/isokoliuk/mcp-searxng:2.0.0@sha256:485544ea18394c8c971f3db0f4f75d61422f7a95aae64fc72ca86118f4f05ce4
  transport: stdio
  env:
    - name: SEARXNG_URL
      value: http://searxng.searxng.svc.cluster.local
  resources:
    requests:
      cpu: 5m
      memory: &memory 65Mi
    limits:
      memory: *memory
