apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: terraform
spec:
  image: hashicorp/terraform-mcp-server:1.1.0@sha256:312d63756b5474df384b1844af55b58ca48cbe0996871e1d6c4239bfcd6fcd29
  transport: stdio
