apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: terraform
spec:
  image: hashicorp/terraform-mcp-server:1.3.0@sha256:423a6b8e2ee06affcf090892f40c86469caba45fd2448ffa8ca5d717a174f7d5
  transport: stdio
  resources:
    requests:
      cpu: 5m
      memory: &memory 86Mi
    limits:
      memory: *memory
