apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich
  namespace: immich
spec:
  interval: 24h
  url: https://immich-app.github.io/immich-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
  labels:
    nfsMount: "true"
spec:
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: app-template
      version: 4.6.x
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      annotations:
        reloader.stakater.com/auto: "true"

    controllers:
      api:
        type: deployment
        strategy: RollingUpdate
        replicas: 2
        labels:
          nfsMount: "true"
        containers:
          main:
            image: &image
              repository: ghcr.io/immich-app/immich-server
              tag: &tag v2.5.6
            env:
              IMMICH_WORKERS_INCLUDE: api
            envFrom:
              - secretRef:
                  name: immich-secret-env
              - configMapRef:
                  name: immich-configmap
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: http
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: http
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 30
            ports:
              - name: http
                containerPort: 2283
                protocol: TCP
              - name: metrics
                containerPort: 8081
                protocol: TCP
            resources:
              limits:
                memory: &apimemory 750Mi
              requests:
                cpu: 155m
                memory: *apimemory
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
        pod: &pod
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
      microservices:
        type: deployment
        strategy: RollingUpdate
        replicas: 2
        labels:
          nfsMount: "true"
        containers:
          main:
            image: *image
            env:
              IMMICH_WORKERS_EXCLUDE: api
            envFrom:
              - secretRef:
                  name: immich-secret-env
              - configMapRef:
                  name: immich-configmap
            resources:
              limits:
                memory: &msmemory 2.5Gi
              requests:
                cpu: 495m
                memory: *msmemory
            ports:
              - name: metrics
                containerPort: 8082
                protocol: TCP
            securityContext: *securityContext
        pod: *pod
      machine-learning:
        type: deployment
        strategy: RollingUpdate
        replicas: 2
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: *tag
            env:
              TRANSFORMERS_CACHE: /cache
              MPLCONFIGDIR: /cache/matplotlib
              HF_XET_CACHE: /cache/huggingface-xet
            envFrom:
              - secretRef:
                  name: immich-secret-env
              - configMapRef:
                  name: immich-configmap
            ports:
              - name: http
                containerPort: 3003
                protocol: TCP
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: http
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: http
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 60
            resources:
              limits:
                memory: &mlmemory 2.5Gi
              requests:
                cpu: 2000m
                memory: *mlmemory
            securityContext: *securityContext
        pod: *pod

    service:
      api:
        controller: api
        primary: true
        ports:
          http:
            port: 80
            primary: true
            targetPort: http
            protocol: HTTP
          metrics:
            port: 8081
            targetPort: metrics
            protocol: HTTP
      microservices:
        controller: microservices
        ports:
          metrics:
            port: 8082
            targetPort: metrics
            protocol: HTTP
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: 80
            targetPort: http
            protocol: HTTP

    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: &host immich.${INTERNAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: api
                  port: http
        tls:
          - hosts:
              - *host
            secretName: immich-ingress-tls

    serviceMonitor:
      api:
        enabled: true
        service:
          identifier: api
        endpoints:
          - port: metrics
            scheme: http
      microservices:
        enabled: true
        service:
          identifier: microservices
        endpoints:
          - port: metrics
            scheme: http

    persistence:
      library:
        enabled: true
        existingClaim: library
        advancedMounts:
          api:
            main:
              - path: /data
          microservices:
            main:
              - path: /data

      external-library:
        type: nfs
        server: 192.168.30.20
        path: /mnt/main/Cluster/Production/ImmichExternalLibrary
        advancedMounts:
          api:
            main:
              - path: /external-library
          microservices:
            main:
              - path: /external-library
      cache:
        type: persistentVolumeClaim
        accessMode: ReadWriteMany
        storageClass: ceph-filesystem
        size: 10Gi
        advancedMounts:
          machine-learning:
            main:
              - path: /cache
      tmpfs:
        type: emptyDir
        advancedMounts:
          machine-learning:
            main:
              - path: /tmp
                subPath: tmp
