apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &app immich

labels:
  - pairs:
      app.kubernetes.io/module: *app

configMapGenerator:
  - name: immich-dashboards
    options:
      labels:
        grafana/dashboard: "true"
      annotations:
        grafana/folder: Immich
    files:
      - dashboard.json

resources:
  - namespace.yaml
  - library.yaml
  - store.yaml
  - pgcluster.yaml
  - dragonfly.yaml
  - network.yaml
  - secrets.yaml
  - configmap.yaml
  - helm.yaml
  - service.yaml
