apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: immich-password-generator
spec:
  length: 64
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: immich-cluster
  namespace: immich
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: infisical
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: immich-password-generator
  template:
    data:
      username: immich
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: immich/postgres
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: immich/postgres
          property: username
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: immich-redis
  namespace: immich
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: infisical
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: immich-password-generator
  template:
    data:
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: immich/redis
          property: password
