apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secret-env
  namespace: immich
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: immich-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        REDIS_URL: |-
          {{- $redisPassword := .redis_password -}}
          {{- $sentinelPassword := .redis_password -}}
          {{- $config := printf `{"sentinels":[{"host":"immich-redis-sentinel-0.immich-redis-sentinel-headless","port":26379,"host":"immich-redis-sentinel-1.immich-redis-sentinel-headless","port":26379,"host":"immich-redis-sentinel-2.immich-redis-sentinel-headless","port":26379}],"name":"myMaster", "password": "%s","sentinelPassword":"%s"}` $redisPassword $sentinelPassword -}}
          ioredis://{{ $config | b64enc }}
        DB_USERNAME: "{{ .dbuser }}"
        DB_PASSWORD: "{{ .dbpass }}"
  data:
    - secretKey: redis_password
      remoteRef:
        key: /immich/REDIS_PASSWORD
    - secretKey: dbuser
      remoteRef:
        key: /immich/POSTGRES_USERNAME
    - secretKey: dbpass
      remoteRef:
        key: /immich/POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-redis
  namespace: immich
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: immich-redis-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: /immich/REDIS_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres
  namespace: immich
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: immich-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: password
      remoteRef:
        key: /immich/POSTGRES_PASSWORD
    - secretKey: username
      remoteRef:
        key: /immich/POSTGRES_USERNAME
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-backup-s3-account
  namespace: immich
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: immich-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: /immich/BACKUP_S3_ACCESS_KEY
    - secretKey: secret_key
      remoteRef:
        key: /immich/BACKUP_S3_SECRET_KEY
