apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/category: infrastructure
      app.kubernetes.io/environment: dev

resources:
  - ../../base/security
  - ../../base/databases
  - ../../base/observability
  - ../../base/platform
  - ../../base/networking

patches:
  - target:
      kind: Secret
      name: secrets
    patch: |-
      - op: replace
        path: /stringData/INTERNAL_DOMAIN
        value: intra.localhost
      - op: replace
        path: /stringData/EXTERNAL_DOMAIN
        value: localhost
      - op: remove
        path: /sops
  - target:
      kind: Kustomization
      name: envoy-gateway-config
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/overlays/dev/networking/envoy-gateway/config
  - target:
      kind: Kustomization
      name: flux-instance
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/overlays/dev/platform/flux/instance
  # Minikube has builtin Cilium
  - target:
      kind: Kustomization
      name: cilium
    patch: |-
      $patch: delete
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: &app cilium
        namespace: &namespace cilium-system
  - target:
      kind: Kustomization
      name: cilium-policies
    patch: |-
      - op: remove
        path: /spec/dependsOn
