apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/category: infrastructure
      app.kubernetes.io/environment: dev

resources:
  - ../../base/security
  - ../../base/databases
  - ../../base/observability
  - ../../base/platform
  - ../../base/networking
  - ../../base/storage

patches:
  - target:
      kind: Secret
      name: secrets
    patch: |-
      - op: replace
        path: /stringData/INTERNAL_DOMAIN
        value: internal.dreadster.dev
      - op: replace
        path: /stringData/EXTERNAL_DOMAIN
        value: dreadster.dev
      - op: remove
        path: /sops
  # - target:
  #     kind: ConfigMap
  #     name: settings
  #   patch: |-
  #     - op: replace
  #       path: /data/EXTERNAL_ADDRESS_POOL
  #       value: 10.7.0.64/29
  - target:
      kind: Kustomization
      name: cilium-config
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/overlays/dev/networking/cilium/config
  - target:
      kind: Kustomization
      name: envoy-gateway-config
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/overlays/dev/networking/envoy-gateway/config
  - target:
      kind: Kustomization
      name: flux-instance
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/overlays/dev/platform/flux/instance
  # Minikube has builtin Cilium
  - target:
      kind: Kustomization
      name: cilium
    patch: |-
      $patch: delete
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: cilium
        namespace: cilium-system
  # Remove cilium-configs dependsOn
  - target:
      kind: Kustomization
      name: cilium-config
    patch: |-
      - op: remove
        path: /spec/dependsOn
  - target:
      kind: Kustomization
      name: cilium-policies
    patch: |-
      - op: remove
        path: /spec/dependsOn
  - target:
      kind: Kustomization
      name: external-dns
    patch: |-
      $patch: delete
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: external-dns
        namespace: external-dns
  - target:
      kind: Kustomization
      name: metrics-server
    patch: |-
      $patch: delete
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: metrics-server
        namespace: metrics-server
  - target:
      kind: Kustomization
      name: netbird-operator
    patch: |-
      $patch: delete
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: netbird-operator
        namespace: netbird
  - target:
      kind: Kustomization
      name: netbird-operator-config
    patch: |-
      $patch: delete
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: netbird-operator-config
        namespace: netbird
  - target:
      kind: Kustomization
      name: rook-ceph-cluster
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/overlays/dev/storage/rook/cluster
      - op: add
        path: /spec/healthChecks
        value:
          - apiVersion: helm.toolkit.fluxcd.io/v2
            kind: HelmRelease
            name: rook-ceph-cluster
            namespace: rook-ceph
          - apiVersion: ceph.rook.io/v1
            kind: CephCluster
            name: rook-ceph
            namespace: rook-ceph
  - target:
      kind: Kustomization
      name: nfs-subdir
    patch: |-
      $patch: delete
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: nfs-subdir
        namespace: nfs-subdir
  - target:
      kind: Kustomization
      name: local-path-storage
    patch: |-
      $patch: delete
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: local-path-storage
        namespace: local-path-storage
