apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/category: infrastructure
      app.kubernetes.io/environment: dev

resources:
  - ../../base/security
  - ../../base/databases
  - ../../base/observability
  - ../../base/platform
  - networking
  - platform

patches:
  - target:
      kind: Secret
      name: secrets
    patch: |-
      - op: replace
        path: /stringData/INTERNAL_DOMAIN
        value: intra.localhost
      - op: replace
        path: /stringData/EXTERNAL_DOMAIN
        value: localhost
      - op: remove
        path: /sops
