apiVersion: v1
kind: Secret
metadata:
    name: secrets
stringData:
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:IE/XUJj+aJfBFbAFH6cBcKDpjA==,iv:WgdvSIrvao8wvDV7QfNo0IIWAYETTP/mG8xgHaRoru0=,tag:weqKLGkkBobcij+iRl8Qfg==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:1E08LlOPqz0PqYL3Cw==,iv:CU5sPp4VAHiQ8Zge1jwGBybwZCtSAS5NTBzbxDjD/Uw=,tag:Esd+A/wzFOETtFn0Ca+BNQ==,type:str]
    HOME_DOMAIN: ENC[AES256_GCM,data:sGMc80HBVu3FEYrcWVBK45YGtC8=,iv:cRcoZYHuoen9b3RiEHJ7hpzUhQxRhXLRKwwB0fiOeyM=,tag:/BYj8nB7TbXWmUImzquFzA==,type:str]
sops:
    age:
        - recipient: age1usemhw8v2nnr5nuxddrc7gsy3525hhv0na4hk2ur7tjara5cp90s7cpeen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPT0IrNWoybURBcTZycXdQ
            YnN2UGhFYjZjVGJObXBmTnRyWGZ0eTc3NHhJCmJNT0NlY1VTTTQxLzRtNHl2NFZk
            YmM0MUdINGlLMy84M3BpRlA3VWhyOE0KLS0tIFpyS1ZzK2FmVHUvemdsMXZxU24v
            RFdFcHJmQnZ2dnlnZzVBMEJ3cEdwRE0KLEOfGoIBtNpgF5QmkPQU33cf6unZuL8C
            q6ztR69QIFTkqblGDpOqk3F85/xtOfinV/q7ypHCk7SqhkT9tX6LiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T23:43:48Z"
    mac: ENC[AES256_GCM,data:BKen7hzLUNY9ifqZbjgt0Xd5sgJAGOizbWNtTzcRB1fpSgT+SWpH9qr9UbAbKAZhUNl042uI5yO+eJ8hWsPx1lGn/a1uZblEid4Rs5mmYpNd5iGLoFwKYmMxMju/s1fhR8yomTsfUREvAv7EcmAc1R5tT7AfedaRbQceAioHL5c=,iv:5TnUkJ2L0ZZU16qG854hstqVTEBEQq++14goupjazUo=,tag:fqXbh8oM2Mh4yyqAzIf9aw==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|secretboxencryptionsecret|bootstraptoken|secret|id)$
    version: 3.12.2
