apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/category: apps
      app.kubernetes.io/environment: dev

resources:
  - authentik
  - harbor
  - immich
  - joplin
  - n8n
  - netbox
  - paperless
  - searxng
  - termix
  - uptime
  - vault
  - vaultwarden
