---
version: "3"

tasks:
  sync:
    desc: Force sync of external secret
    cmd: kubectl -n {{ .NS }} annotate externalsecret {{ .NAME }} force-sync=$(date +%s) --overwrite
    requires:
      vars:
        - NAME
        - NS
    preconditions:
      - sh: which kubectl
        msg: kubectl is not installed
