apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &app litellm

labels:
  - pairs:
      app.kubernetes.io/module: *app

configMapGenerator:
  - name: litellm-proxy-config
    options:
      disableNameSuffixHash: true
    files:
      - resources/config.yaml

resources:
  - namespace.yaml
  - store.yaml
  - pgcluster.yaml
  - network.yaml
  - secrets.yaml
  - dragonfly.yaml
  - pvc.yaml
  - httproute.yaml
  - helm.yaml
  - servicemonitor.yaml
