apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: litellm-cluster
  namespace: litellm
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "disabled"
spec:
  bootstrap:
    recovery: null
    initdb:
      database: litellm
      owner: litellm
      secret:
        name: litellm-cluster-credentials

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backup-store
        serverName: litellm-cluster