name: Docker

on:
  pull_request:
    branches:
      - main
    paths:
      - "docker/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Docker Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Go Task
        uses: go-task/setup-task@a00fbb05ce67b35648be3c78cbc9fd85354c757e # v2.2.0
        with:
          version: "3.x"

      - name: Validate
        run: task docker:validate
