name: Flux Local

on:
  pull_request:
    branches:
      - main
    paths:
      - "kubernetes/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Flux Local Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@5adad89dcce7b79f20274ae8e112bcec7bd46764 # v2.8.5

      - name: Flux Local Test
        uses: allenporter/flux-local/action/test@4d666add25002f550dc0dbe8b2b2f25859169b34 # 8.2.0
        with:
          path: kubernetes/clusters/production
          enable-helm: true
          debug: true

  diff:
    name: Flux Local Diff
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        resources: ["helmrelease", "kustomization"]
      fail-fast: false
    steps:
      - name: Checkout Pull Request Branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@5adad89dcce7b79f20274ae8e112bcec7bd46764 # v2.8.5

      - name: Flux Local Diff
        uses: allenporter/flux-local/action/diff@4d666add25002f550dc0dbe8b2b2f25859169b34 # 8.2.0
        id: diff
        with:
          live-branch: ${{ github.event.repository.default_branch }}
          path: kubernetes/clusters/production
          resource: ${{matrix.resources}}
          sources: flux-system
          debug: true

      - name: Generate Token
        if: ${{ steps.diff.outputs.diff != '' }}
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Add Comment
        if: ${{ steps.diff.outputs.diff != '' }}
        uses: mshick/add-pr-comment@64b8e914979889d746c99dea15a76e77ef64580a # v3
        with:
          repo-token: "${{ steps.app-token.outputs.token }}"
          message-id: "${{ github.event.pull_request.number }}/kubernetes/${{ matrix.resources }}"
          message-failure: Diff was not successful
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
