name: Validate Kubernetes Manifests

on:
  pull_request:
    branches:
      - main
    paths:
      - "kubernetes/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Flate Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Flate
        uses: home-operations/flate/action@631b76b69c4e58c6f4d1cb01e23616fa61aebafa # v0.6.5

      - name: Flate Test
        run: flate test all --path kubernetes/clusters/production

  diff:
    name: Flate Diff
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Pull Request Branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Flate
        uses: home-operations/flate/action@631b76b69c4e58c6f4d1cb01e23616fa61aebafa # v0.6.5
        with:
          base: ${{ github.event.repository.default_branch }}

      - name: Flate Diff
        id: diff
        run: |
          flate diff all --path kubernetes/clusters/production -o diff > diff.txt
          {
            echo 'diff<<EOF'
            cat diff.txt
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Generate Token
        if: ${{ steps.diff.outputs.diff != '' }}
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Add Comment
        if: ${{ steps.diff.outputs.diff != '' }}
        uses: mshick/add-pr-comment@ec328af66588ab8f77cdeb2c264f14aba45bbf59 # v3.12.0
        with:
          repo-token: "${{ steps.app-token.outputs.token }}"
          message-id: "${{ github.event.pull_request.number }}/kubernetes"
          message-failure: Diff was not successful
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
