apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../base/networking/cilium/config

patches:
  - target:
      kind: CiliumLoadBalancerIPPool
      name: default-pool
    patch: |
      $patch: delete
      apiVersion: cilium.io/v2
      kind: CiliumLoadBalancerIPPool
      metadata:
        name: default-pool
