apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../base/networking/cilium/config

patches:
  - target:
      kind: CiliumLoadBalancerIPPool
      name: default-pool
    patch: |
      $patch: delete
      apiVersion: cilium.io/v2
      kind: CiliumLoadBalancerIPPool
      metadata:
        name: default-pool

  - target:
      kind: CiliumClusterwideNetworkPolicy
      name: allow-cnpg-cluster
    patch: |-
      - op: replace
        path: /spec/egress/0
        value:
          toEndpoints:
            - matchLabels:
                io.kubernetes.pod.namespace: rook-ceph
                app.kubernetes.io/name: ceph-rgw
          toPorts:
            - ports:
                - port: "8080"
                  protocol: TCP
