name: traefik
working_dir: docker/mgmt/traefik
compose_files:
  - compose.yaml
---
name: it-tools
working_dir: docker/mgmt/it-tools
compose_files:
  - compose.yaml
---
name: speedtracker
working_dir: docker/mgmt/speedtracker
compose_files:
  - compose.yaml
---
name: home-assistant
working_dir: docker/mgmt/home-assistant
env_files:
  - ../base.env
compose_files:
  - compose.yaml
