name: traefik
working_dir: docker/mgmt/traefik
compose_files:
  - compose.yaml
---
name: it-tools
working_dir: docker/mgmt/it-tools
compose_files:
  - compose.yaml
---
name: speedtracker
working_dir: docker/mgmt/speedtracker
compose_files:
  - compose.yaml
---
name: home-assistant
working_dir: docker/mgmt/home-assistant
compose_files:
  - compose.yaml
---
name: omada-controller
working_dir: docker/mgmt/omada-controller
compose_files:
  - compose.yaml
---
name: dockhand
working_dir: docker/mgmt/dockhand
compose_files:
  - compose.yaml
---
name: peanut
working_dir: docker/mgmt/peanut
compose_files:
  - compose.yaml
---
name: duplicati
working_dir: docker/mgmt/duplicati
compose_files:
  - compose.yaml
---
name: stirling-pdf
working_dir: docker/mgmt/stirling-pdf
compose_files:
  - compose.yaml
---
name: appraise
working_dir: docker/mgmt/appraise
compose_files:
  - compose.yaml
---
name: infisical
working_dir: docker/mgmt/infisical
compose_files:
  - compose.yaml
---
name: databasus
working_dir: docker/mgmt/databasus
compose_files:
  - compose.yaml
---
name: arcane
working_dir: docker/mgmt/arcane
compose_files:
  - compose.yaml
