apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../base/observability/thanos/app

patches:
  - target:
      kind: ExternalSecret
      name: thanos-object-store
    patch: |-
      - op: replace
        path: /spec/target/template/data/objstore.yml
        value: |
          type: S3
          config:
            bucket: thanos
            endpoint: rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local
            access_key: {{.AWS_ACCESS_KEY_ID}}
            secret_key: {{.AWS_SECRET_ACCESS_KEY}}
            insecure: true
  - path: helm.yaml
    target:
      kind: HelmRelease
      name: thanos
